### ISSUE TITLE
Embrace the var(--idea)

### ISSUE THREAD

**Issue by garygreen** [tailwindcss/tailwindcss#1022]
At the moment tailwind uses a custom `config()` to provide variable options:

```css
background-color: config('colors.blue');
```

To me this has always felt a bit awkward because it seems very similar to this:

```css
background-color: var(--color-blue)
```

I know there is a community project which exposes all of tailwinds config options as variables, but wondered if it would be a good idea to consider this change for core as it embraces standard ? Would there be any downsides to this approach?

**Comment by adamwathan** [comment]
I'm going to explore some ideas with CSS custom properties a bit more soon, but even so there will always be a use case for the `theme` function (it was renamed for 1.0), mainly when you need the underlying color to be known at build time.

For example, if you wanted to use a library like `postcss-color-function` to manipulate the alpha channel of a color:

```css
box-shadow: 0 0 3px color(theme('red.500') a(25%));
```

This wouldn't work with CSS custom properties because the color needs to be fully resolved for the `color` function to work with it.

**Comment by garygreen** [comment]
> This wouldn't work with CSS custom properties because the color needs to be fully resolved for the color function to work with it.

Hmm, interesting. Could you not use [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) to convert the variables into static values and then I would assume `postcss-color-function` would be able to then consume it?

**Comment by adamwathan** [comment]
No because that plugin would convert it to something like this before feeding it into `postcss-color-function`:

```css
.red-shadow {
  box-shadow: 0 0 3px color(#F56565 a(25%));
  box-shadow: 0 0 3px color(var(--colors-red-500) a(25%));
}
```

...and `postcss-color-function` would fall over on the second property.

I think we will basically always support the `theme` function but it could be useful to expose all of the theme values as CSS custom properties in addition. Will play with it some more probably next month.

**Comment by BinarySpike** [comment]
I developed a [postcss plugin](https://github.com/binaryspike/postcss-compose) that meets my use cases outside of `theme`.

I was previously using [tailwind-css-variables](https://github.com/omarkhatibco/tailwind-css-variables) and an `each` plugin for postcss.  That was cumbersome though.

**Comment by adamwathan** [comment]
Going to close this particular issue as I have no plans to replace `theme` with CSS custom properties.
