### ISSUE TITLE
@screenAbove and @screenBelow

### ISSUE THREAD

**Issue by garygreen** [tailwindcss/tailwindcss#1023]
At the moment you can only design in a "mobile" first like approach:

```css
@screen sm {
   .alert {
       ....
    }
}
```

To me this doesn't read intuitively because it sounds like it's saying "on small screens... apply this" when in fact it's actually saying "on small screens and above"

When you use `@media` declarations it's obvious what it's doing because you have to specifically define `min-width` and/or `max-width` constraints, so it's patently obvious what it's doing and mostly importantly *when*.

So would it be a good idea to have two new variants where you can design in a non-mobile first approach (sometimes this is needed in your application) whilst making it easier to understand the constraint when it applies those styles:

```css
@screenAbove sm {
   .alert {
       ....
    }
}

@screenBelow lg {
   .alert {
       ....
    }
}
```

To me this style is far more intuitive to understand. What do you think?

**Comment by garygreen** [comment]
Alternatively, maybe tailwind can embrace a new upcoming CSS standard: https://github.com/postcss/postcss-custom-media

This may tie in with #1022

**Comment by adamwathan** [comment]
No plans to add anything like screenAbove or screenBelow because media queries in Tailwind are already customizable in terms of if they are min-width, max-width, or fixed range:

https://tailwindcss.com/docs/breakpoints#max-width-breakpoints

Parsing that out to try and make something like screenBelow work no matter how the media query is actually declared sounds kinda gross and annoying.

Going to say no for now but if enough people really want something like this we can always discuss it again.

In the mean time you can always do this:

```css
@media (min-width: theme('screens.sm')) {
   .alert {
       ....
    }
}

@media (max-width: calc(theme('screens.sm') - 1px)) {
   .alert {
       ....
    }
}
```
