### ISSUE TITLE
[Bug] `focus:shadow-outline` on button not working in Firefox or Safari

### ISSUE THREAD

**Issue by gawlk** [tailwindcss/tailwindcss#1029]
Hi !

I've been testing your great library and I don't know if you noticed but the `focus:shadow-outline` class doesn't work in Firefox and Safari but does work in Chromium.

The weird thing is that both `shadow-outline` and `hover:shadow-outline` work everywhere.

I also tried [buttons](https://tailwindcss.com/docs/box-shadow/#outline-shadow) of your documentation directly and they don't work either, so it's not a problem on my side.

**Comment by tlgreg** [comment]
It works here on Firefox 69.0b4 on Windows.
![ff69](https://i.imgur.com/ECQF6T9.png)
Pen: https://codepen.io/tlgreg/pen/xovRYq

**Comment by gawlk** [comment]
> It works here on Firefox 69.0b4 on Windows.
> ![ff69](https://camo.githubusercontent.com/0d3357786754085ab538eadb246b4a912806869b/68747470733a2f2f692e696d6775722e636f6d2f454351463654392e706e67)
> Pen: https://codepen.io/tlgreg/pen/xovRYq

Weirdly, the `focus:shadow-outline` on the input works everywhere but the one on the input still doesn't

**Comment by adamwathan** [comment]
Even if this doesn't work it't not really possible for it to be a Tailwind-specific problem, all we're doing is creating a class that adds a box shadow. So if the Tailwind class isn't working, writing the CSS by hand must not be working either.

It all works on my machine for what it's worth:

![image](https://user-images.githubusercontent.com/4323180/61291377-60116400-a79c-11e9-99b9-622ce5066844.png)

![image](https://user-images.githubusercontent.com/4323180/61291403-70c1da00-a79c-11e9-9c4b-829b8435c423.png)

![image](https://user-images.githubusercontent.com/4323180/61291424-7ddec900-a79c-11e9-82e7-ec31af72b56a.png)

Sounds like it's something specific to your environment where box-shadows on buttons don't work?

Closing this since it's not a Tailwind problem but happy to continue troubleshooting in this thread.

**Comment by gawlk** [comment]
No problem, I understand, this is extremely weird tough.
I just installed Safari Preview and it doesn't work either

**Comment by adamwathan** [comment]
Do other box shadows work? If you look in dev tools are the styles active when you manually trigger a focus on that element?

![image](https://user-images.githubusercontent.com/4323180/61292132-6d2f5280-a79e-11e9-8bf3-e4553893337b.png)

**Comment by gawlk** [comment]
Yes, the one on the input works !

I was just about to write that when I turn it the :hover on manually, the shadow does appear !
