### ISSUE TITLE
Is the class name dot optional for the @apply directive ?

### ISSUE THREAD

**Issue by lamberttraccard** [tailwindcss/tailwindcss#106]
Hi,

I noticed that the class name dot is facultative when use with the @apply directive.

`.foo {@apply .text-white;}`  `.foo {@apply text-white;}` 

Both are working but should we stick with the dot syntax or can we safely use both ?

**Comment by m2de** [comment]
fwiw, I prefer using the non-dot syntax.

**Comment by jameslkingsley** [comment]
Non-dot syntax is preferable imo, especially since when you extract a set of classes to components you can just copy and paste after the `@apply`, instead of having to add a dot in-front of each class.

**Comment by adamwathan** [comment]
We're still on the fence about what syntax we want to actively encourage. Personally, I prefer using the dot prefix because you are in a CSS file and trying to reference a class name, and in CSS class names start with dots.

The dot prefix is also more familiar for people used to using something like `@extend` in Less or Sass:

```
.error {
    @extend .text-red;
}
```

That said, the reason we added support for no dot prefix was the reason that was mentioned: it does make it a bit easier to paste in a class list from your HTML when extracting a component.

Even still, I'm inclined to encourage using the dot prefix because if we choose to stop supporting one of them, the no-prefix option is the one I'd expect we'd drop. If anything, maybe it would be replaced by another directive that took a form more like:

```
.error {
  @classes "text-red bg-red-lighter border border-red";
}
```

**Comment by adamwathan** [comment]
Going to close this; we don't have explicit plans to stop supporting the no-prefix option but we only plan to document the `@apply .class` version, so I would recommend using that syntax.

**Comment by evenfrost** [comment]
Hey @adamwathan, was looking through the docs and noticed the dots in `@apply` calls were removed. Does [this](https://github.com/tailwindcss/docs/commit/6cbb214a71f78019624b6dda9f3247c30361f7b1) mean that no-dot syntax is preferable now?

**Comment by adamwathan** [comment]
@evenfrost Yeah I stopped using the dot prefix myself so decided that's the one I want to encourage. Both continue to work though 👍

**Comment by evenfrost** [comment]
FWIW, dot syntax is [removed in Tailwind 2.0](https://tailwindcss.com/docs/upgrading-to-v2#remove-leading-dot-from-apply-statements).
