### ISSUE TITLE
IE Bugs

### ISSUE THREAD

**Issue by Chazza** [tailwindcss/tailwindcss#1085]
Hi there,
I've been building a site and ended up coming across that tailwind seems to be slightly buggy (on default playground) within IE11.

Examples:
Playground: https://i.imgur.com/7gpvqXm.png
Another Site: https://spoof.gg/

They appear slightly broken, perhaps an overflow issue? (going by a user in the discord)

**Comment by tlgreg** [comment]
There are several issues with IE11 still, most of it has some workaround. Dealing with css properties directly (utilities) instead of components these will likely come up.
You'll mostly encounter flexbox issues: https://github.com/philipwalton/flexbugs

In the case of the playground:
- A workaround for the wrapping issue is to add some overflow property to the block, `overflow-auto` should work too.
- The issue with the logo might seem like flexbox issue but it's an SVG sizing issue, which can get tricky too. Unfortunately, IE also handles this poorly. Especially when you try to size something by its height while preserving aspect-ratio. An article on the subject in general (there is also a good one in its comments): https://css-tricks.com/scale-svg/

Some similar issues with the other site:
- SVGs need sizes defined.
- In the hero block, the wrapper flex element should have the `items-center`, not the child, then `my-auto` can be removed too.

**Comment by adamwathan** [comment]
Not really the realm of Tailwind to fix this stuff, although we should fix the playground demo. Since Tailwind is just utilities it's up to you to use the utilities in a way that works in the browsers you want to support.

**Comment by Chazza** [comment]
Thanks for the feedback!
