### ISSUE TITLE
[Documentation] Documentation about how to build locally to test local changes

### ISSUE THREAD

**Issue by Larissagilliane** [tailwindcss/tailwindcss#1093]
While doing a new feature i didn't find any documentation about building the project locally to see the changes. 
I think this would be helpful for newcomers. 

@adamwathan

**Comment by hacknug** [comment]
That would be on [the contribution guidelines](https://github.com/tailwindcss/tailwindcss/blob/master/.github/CONTRIBUTING.md).

Note that there's no mention on how to build the project like you asked for and that's probably because it only need to be built before releasing a new version (during development, running the tests would be enough if I'm not missing anything here).

You can see the different scripts available in the project's [`package.json`](https://github.com/tailwindcss/tailwindcss/blob/master/package.json#L19-L25).

**Comment by adamwathan** [comment]
Added some instructions here 👍 

https://github.com/tailwindcss/tailwindcss/commit/9e7fe850a4e4b259ee88d1280764d0ce3d961e97
