### ISSUE TITLE
Parcel Tailwind documentation

### ISSUE THREAD

**Issue by imam** [tailwindcss/tailwindcss#1153]
Hello,

I want to add parcel and tailwind integration to documentation, I just want to request permission to do so  before I write anything :)

**Comment by tehpsalmist** [comment]
Hey @imam I think you can just open up a PR, and if its good, they'll accept it or give you some feedback. I'd be interested to see what you come up with, as parcel is my go-to bunder these days.

**Comment by adamwathan** [comment]
Hey! Because there are so many possible environments where someone might want to use Tailwind, I decided it makes more sense to maintain the https://github.com/tailwindcss/setup-examples instead of continuing to add more and more to the docs. I need to merge a bunch of PRs there and change the installation instructions to link there instead but if you'd like to PR your Parcel example to that repo that would be great, thanks!

**Comment by imam** [comment]
That's great to hear, I'll start as soon as I can, thank you @adamwathan

**Comment by luxlogica** [comment]
@adamwathan Parcel is a modern, increasingly popular bundler - an alternative to Webpack/Gulp/Laravel Mix/Brunch/etc. It has gained tremendous popularity due to its ease of configuration - much easier than all the competition - speed, and amazing built-in features. For example: it has PostCSS baked-in, and will automatically install modules if you require them. 

As a consequence, configuring Parcel to bundle Tailwind might indeed be slightly different - and very likely easier - than with other bundlers, and therefore well worth the inclusion in the “Installation” page of the docs (under item 4, “Process your CSS with Tailwind”, along with the other bundlers).
