### ISSUE TITLE
Gradients don't work with bg prefix

### ISSUE THREAD

**Issue by Ragura** [tailwindcss/tailwindcss#1154]
First of all, working with Tailwind CSS is an amazing experience. I know this is a hobby project, so I won't waste too much of your time.

When extending the default config with a new color that is a linear gradient, the color will not work with the `bg-` prefix. It will however be recognized if you use it within a style block with the `theme()` function.

```js
theme: {
    extend: {
      colors: {
        "brand-gradient": "linear-gradient(90deg, #337cd5 0%, #66db9f 100%)"
      }
    }
  },
``` 

This will not work:

```html
<div class="bg-brand-gradient">
``` 

Whereas creating this selector and attaching the class to the above div will work:

```css
.gradient-test: {
  background: theme("colors.brand-gradient");
}
```

Any idea what's going on? I might be misunderstanding the auto-generation description in the docs.

**Comment by adamwathan** [comment]
Hey @Ragura thanks for the kind words! The issue I think is that background gradients need to be implemented using the `background-image` property, and background colors using the `background-color` property, and Tailwind uses the full `background-color` property for colors rather than the `background` shorthand which would work for both.

This is probably something we will add to core eventually but in the mean time here are two Tailwind plugins you could install that would solve your problem (taking slightly different approaches):

https://github.com/hacknug/tailwindcss-background-extended
https://github.com/benface/tailwindcss-gradients

**Comment by Ragura** [comment]
Ah, that makes a lot of sense actually!

Will definitely use one of those plugins until this gets integrated into the core build. Thanks for the incredibly quick reply!
