### ISSUE TITLE
Input (::placeholder) utilities

### ISSUE THREAD

**Issue by glenngijsberts** [tailwindcss/tailwindcss#125]
Last days I've been working with Tailwind and I have just so much fun 😀 

I was looking for some input utilities but couldn't find them. Maybe I've looked over them, I don't know. I was specific looking for pseudo elements/classes like `::placerholder`, `::invalid` and so on. 

I think it would be great to include them, maybe it is already included in the plans for new releases, or maybe not at all. Thanks anyway!

**Comment by reinink** [comment]
Hey there @glenngijsberts! We don't have any `placeholder` or `invalid` utilities right now. They are similar to `hover`, `active` and `focus`, which don't exist (except for some hover states).

The reason is that adding these states for each utility in Tailwind would cause the outputted CSS file size to grow substantially. Ideally it would be great to have these states available on all utilities, but practically it's not smart.

That said, we're are already working on a system where you can enable or disable the responsive, active, focus and hover states on a per module basis.

This is similar to issue #121.

**Comment by adamwathan** [comment]
Consolidate into #136.
