### ISSUE TITLE
1.2.0: Table utilities: rename table groups

### ISSUE THREAD

**Issue by Illyism** [tailwindcss/tailwindcss#1304]
I would propose to rename the table groups to a shorter former that also still makes sense: just use the HTML element names instead of the CSS names.

For example:

- table-header-group => thead
- table-row-group => tbody
- table-footer-group => tfoot
- table-row => tr
- table-cell => th, td

This would allow one to quickly convert a table to a css-only table and help people grok the system.

```
<table>
  <tbody>
    <tr>
       <td>hi</td>
    </tr>
  </tbody>
</table>
```

```
<div class="table">
  <div class="tbody">
    <div class="tr">
       <div class="td">hi</div>
    </div>
  </div>
</div>
```

**Comment by adamwathan** [comment]
I do kinda like this idea but since table-row and table-cell have been around for over two years now I think it's best to just stick with the existing convention even if it means longer class names for the header/row/footer groups, otherwise we'd be introducing either inconsistency or a breaking change.

Thanks for the suggestion!
