### ISSUE TITLE
Custom breakpoint overrides the styles of default breakpoints

### ISSUE THREAD

**Issue by mayankverr** [tailwindcss/tailwindcss#1319]
I extended the breakpoints by adding a custom one 'xs': '520px', here is what my tailwind.config.js file looks like, I also added some height and widths
![Annotation 2020-01-19 180900](https://user-images.githubusercontent.com/54323745/72681351-997ab180-3ae8-11ea-91f2-1eb58d77b3fd.jpg)

The problem is that when I apply height and width to the 'xs' breakpoint and then go on to set different height and width for 'md' & 'lg' they get overridden by the styles of 'xs' even when screen size is greater than 'md'
![Annotation 2020-01-19 181343](https://user-images.githubusercontent.com/54323745/72681451-c1b6e000-3ae9-11ea-8474-600f56e6710e.jpg)
Here my window size is greater than 1024px
![Annotation 2020-01-19 181852](https://user-images.githubusercontent.com/54323745/72681472-fb87e680-3ae9-11ea-8823-e5389a5e4626.jpg)

and if I remove the 'xs' breakpoint then every breakpoint works fine
![Annotation 2020-01-19 181413-no-xs](https://user-images.githubusercontent.com/54323745/72681459-dc895480-3ae9-11ea-9979-2d412cbece0a.jpg)
![Annotation 2020-01-19 183652](https://user-images.githubusercontent.com/54323745/72681549-b617e900-3aea-11ea-829b-baf1df68d84b.jpg)

**Comment by tlgreg** [comment]
Order matters and `extend` will put everything after the default values. So it works if you want to add a bigger breakpoint, but not for smaller ones.
A workaround:
```js
const { screens } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    screens: {
      xs: '520px',
      ...screens,
    },
  },
}
```

**Comment by adamwathan** [comment]
Yep @tlgreg nailed it 👍🏻 Hope that helps!

**Comment by mayankverr** [comment]
@tlgreg thank you!

**Comment by sfiquet** [comment]
It would be great if this could be spelled out in the documentation.

**Comment by tmharryfrancis** [comment]
I'm running into this problem, and the answer from @tlgreg hasn't fixed it.

My config:
`const { screens } = require('tailwindcss/defaultTheme')`
...
`screens: {
                'xs': {'min': '500px'},
                ...screens,
                'xl': {'min': '1400px'},
                'until-xs': {'max': '500px'},
                'until-sm': {'max': '640px'},
                'until-md': {'max': '768px'},
                'until-lg': {'max': '1024px'},
                'until-xl': {'max': '1400px'},
            },`

Any ideas?

**Comment by cozzbie** [comment]
Hi @tmharryfrancis has this been fixed? If not let me know. It might be a cache issue.

**Comment by TheMangoTrain** [comment]
@tmharryfrancis Perhaps an issue with XL? There's a default XL already within "...screens" and you're declaring it again in your custom. Or you've got two "screens" in this context; just to be safe maybe label the first one "screensDefault" ?

**Comment by TheMangoTrain** [comment]
> It would be great if this could be spelled out in the documentation.

I second this. It didn't seem obvious to me that I had to import-or-redefine the original breakpoints in order to simply inject one new breakpoint.

e.g.

I thought doing this would still keep the original breakpoints:
```
    screens: {
        'xs': '480px',
    }
```

**Comment by adamwathan** [comment]
We do explain it here:

https://tailwindcss.com/docs/theme#extending-the-default-theme

But I agree it would be good to have a dedicated heading on the breakpoints page for "adding breakpoints in addition to the defaults" that explain it again. The hardest part about documenting a project like this is figuring out what is an acceptable level of redundancy. It's ridiculous how many times the same concept is re-explained the docs as it is 😅

**Comment by codementation** [comment]
Hi.  I'm switching over to Tailwind from Bootstrap and also ran into this same issue.
According to the documentation that @adamwathan linked (which I did read beforehand twice) it clearly states that,  _"if you wanted to add an extra breakpoint but preserve the existing ones, you could extend the screens property"_

Which I originally did in accordance with the provided example:
```
theme: {
    extend: {
    // Adds a new breakpoint in addition to the default breakpoints
    screens: {
        'xs': '360px',
    }
}
```

However, due to Tailwind using `min-width` media queries, this clobbered all of my other media queries as described by @nooblyf 

@tlgreg solution works for me, but I would concur that the docs, as written, lead the user to believe that one can implicitly   _**preserve** the existing breakpoints_ by extending the theme.  The statement in a subsequent paragraph states that, _"Any keys you do not provide will be inherited from the default theme."_  While technically true, this does not explain that custom breakpoints will be prepended and cause higher breakpoints than the one you define to be nullified.  

Just my $.02, but to make this more n00b friendly, I would suggest maybe adding something along the lines of...

_Note: Tailwind will prepend any specified custom screen theme extensions to the default theme. This means that you specifiy a breakpoint smaller than any of the default theme's breakpoints, then your media query will override all of the breakpoints of the default theme that are larger than the custom screens that you defined. For breakpoints larger than the default 1536px this is not an issue.  However, If you wish to append a smaller screen size, then instead of extending the default theme, define a theme override and append the default screens to yours like so:_

```
const { screens } = require('tailwindcss/defaultTheme')
module.exports = {
  theme: {
    screens: {
      xs: '360px',
      ...screens,
    },
  },
}
```

**Comment by TeemuKoivisto** [comment]
Hey, this issue this still occurs. Or may I say, a bug.

```js
const { screens } = require('tailwindcss/defaultTheme')

module.exports = {
  purge: {
    content: ['./src/**/*.{js,ts,jsx,tsx}'],
    options: {
      keyframes: true,
    },
  },
  darkMode: 'class', // 'media' or 'class'
  theme: {
    extend: {
      screens: {
        xs: '480px',
        ...screens,
      }
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
```

With this config, my `xs` styles still override my `md` styles. I think Tailwind is not ordering the properties correctly by the pixel size. And nope, it's not a cache issue.

**Comment by adamwathan** [comment]
@TeemuKoivisto Everything in Tailwind can be overridden or extended, including screens, so it would introduce some complexity to kinda special case it. I think long term a better approach would be to sort screens for people automatically but there's a chance that would annoy people who wanted control over the order themselves. General recommendation is just replace the screens with your own set of screens, in your own order, like you've discovered 👍🏻

**Comment by longtimedeveloper** [comment]
@TeemuKoivisto your code works.  Extending screens with smaller values is a non-starter, I had to override screens and use your above ... screens code.  

Thank you very much.  

My version numbers.

```
  "devDependencies": {
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.15",
    "tailwindcss": "^2.1.2"
  }
```

**Comment by pil0u** [comment]
This thread helped me understand how Tailwind extends custom classes, i.e. _appends_ them to default ones.

Since the order **matters** for media queries breakpoints, [I wrote a gist that sums it up](https://gist.github.com/pil0u/2147a996ea855ad550df5d66c20bbe03).
If you want to make sure that your custom breakpoints actually work as intended, [this simple gist](https://gist.github.com/pil0u/1500c6579980ebe38f8d22f9e36e8b7b) can be proven useful.

**Comment by IgorLo** [comment]
It seems like provided workarounds work does not work with tailwind ^3.0.18
I have tried both workarounds, importing defaultTheme.screens too

<img width="260" alt="image" src="https://user-images.githubusercontent.com/22037004/155609033-273cb003-bd05-4710-9b65-fb6ed24b3ad1.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/22037004/155609078-c8080571-8c86-48f1-81de-4c817402dd91.png">

**Comment by IgorLo** [comment]
> It seems like provided workarounds work does not work with tailwind ^3.0.18 I have tried both workarounds, importing defaultTheme.screens too
> 
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/22037004/155609033-273cb003-bd05-4710-9b65-fb6ed24b3ad1.png">
> 
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/22037004/155609078-c8080571-8c86-48f1-81de-4c817402dd91.png">

Sorry, i was not supposed to put 'screens' in 'extend' - just put them next to 'extend' - seems to work

**Comment by darrenmuliawan** [comment]
Hey, I got the same issue where I have className="w-full lg:w-[40vw]" and w-full overrides w-[40vw] even on lg screen. I did not put the screens under extend

![image](https://github.com/tailwindlabs/tailwindcss/assets/31380437/84eebaee-a6f7-4820-a521-48a22136a9ca)

**Comment by omattman** [comment]
+1 on this issue and very much similar to the example provided by @darrenmuliawan
