### ISSUE TITLE
[config] Maximum call stack size exceeded after overriding gray

### ISSUE THREAD

**Issue by MikeYermolayev** [tailwindcss/tailwindcss#1325]
Hello,

I'm facing one very strange issue when I override default config with my colors.

Here is part of my config:
![image](https://user-images.githubusercontent.com/8783498/72929528-0bfac400-3d6b-11ea-8f1a-75702b725bd7.png)

As you can see I override colors and want to make darker ones referencing values from the theme.

But when I'm trying to build the styles with postcss I receive this error 
![image](https://user-images.githubusercontent.com/8783498/72929634-495f5180-3d6b-11ea-9294-6c2fa80c6f54.png)

And what's the most interesting part when I delete definition of `gray` color or simply rename it to other word(e.g. 'qwe') then it builds OK

What can be the reasons? Thanks in advance

"tailwindcss": "1.1.4",
"postcss-cli": "7.1.0",

**Comment by adamwathan** [comment]
You've created an infinitely recursive call because your `gray` colors depend on themselves — `theme('colors.gray')` is trying to return your entire `gray` color object but to compute that color object it needs to call `theme('colors.gray')` but to computer _that_ object it needs to call `theme('colors.gray')` ad infinitum.

Best bet is to compute all this stuff in a variable outside of the main config object and then just reference it below.


```js
const baseColors = {
  gray: '#DDDDDD',
  pumpkin: '#0C0C0C',
  // ...
}

module.exports = {
  theme: {
    colors: {
      gray: {
        default: baseColors.gray,
        dark: darken(0.1, baseColors.gray),
       },
      pumpkin: {
        default: baseColors.pumpkin,
        dark: darken(0.1, baseColors.pumpkin),
       },
    }
  }
}
```

**Comment by MikeYermolayev** [comment]
Thanks for such a fast reply!

Yes, that was my first thought but I was totally surprised when I found out that it doesn't work only with `gray` word. Any thoughts why it works without it?

At start I was going with outside variable approach but for some reason Figma Tailwind plugin doesn't work when some variables are defined outside of module.exports ... But that's a different story)
