### ISSUE TITLE
Unresolved values when extend config provided by a plugin (resolveConfig and deeply nested objects issue)

### ISSUE THREAD

**Issue by qntndev** [tailwindcss/tailwindcss#1330]
Hey @adamwathan, 
In [v1.2.0-canaray.4](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.2.0-canary.4) release, you [Allow plugins to extend the user's config](https://github.com/tailwindcss/tailwindcss/releases#user-content-allow-plugins-to-extend-the-user-s-config) so I give it a try and run into an unexpected behavior. If plugin exposes a config theme with a nested structure (deeply in more than one level), when the user extends the config to override some values in `tailwind.config.js` some keys are kicked off during the merge process.

Here is some code to describe the issue: 

My forms plugin exposes `borderColor` and `color` keys for default form fields who inherit from defaults Tailwind `borderColor` and `color` value. 
I use this config on my `form-field` class as part of the `addComponents` function.

```javascript
//forms.js
const plugin = require('tailwindcss/plugin')
const resolveConfig = require('tailwindcss/resolveConfig')
const defaultTheme = resolveConfig(require('tailwindcss/defaultConfig')).theme;

module.exports = plugin(function ({ addComponents, theme }) {
  config = theme('forms');
  addComponents([
    {
      '.form-field': {
        borderColor: config.formField.default.borderColor,
        color: config.formField.default.color

        //...
      }
    }
  ]);
},
{
  theme: {
    forms: {
      formField: {
        default: {
          borderColor: defaultTheme.colors.blue[500],
          color: defaultTheme.colors.black
        }
        //...
      }
    }
  }
})
```
If the user don't set a `forms` key in the `theme.extend` part of his config, the config is properly resolved, but if he wants to override some values, he gets an error : `Cannot read property 'borderColor' of undefined` because all keys of the `default` Object provided in my forms plugin are kicked out during the merge process (resolveConfig ?)

I expect from the _extend_ functionality to keep all keys form my `forms.formField.default` Object and override only the `color` one.

```javascript
//tailwind.config.js
module.exports = {
  theme: {
   extend: {
      forms: theme => ({
        formField: {
          default: {
            color: theme('colors.blue.500')
          }
        }
      })
    }
  },
  plugins: [
    require('./assets/css/plugins/forms')
  ]
}
```

> This PR makes it possible for third-party plugins to provide a config object in the same format as Tailwind's regular config object that will be intelligently merged with the user's config as part of the config resolution process.

Regarding this, I can read in PR note that the config _will be intelligently merged with the user's config_ so I don't really know what is the process but hopefully this is a bug.

From my point of view, the _extend_ theme functionality should merge deeply nested Objects as the Lodash [`defaultsDeep`](https://lodash.com/docs/4.17.15#defaultsDeep) function do and keep every keys and values provided in the plugin's config unless the user redefined a shallow key in his `theme` config or override a value in his `theme.extend` config.

**Comment by adamwathan** [comment]
`extend` only merges one level deep currently, has been the case for everything since 1.0 was released.

We can think through if there are any negative consequences to a deep merge though. One fear I have is that it could break how `fontFamily` works since fonts are specified using an array, and if we deep merge those arrays will get merged even though the user is actually trying to replace the array.

**Comment by adamwathan** [comment]
Thinking through this more, if we deep merge, then there is no way to override an entire nested key. No plans to make changes here right now since this is the only time this issue has come up, but not opposed to exploring again in the future if this becomes a universally agreed point of issue for many users (which it very well may as more and more complex plugins are authored).

For now I would recommend exposing your default configuration to end users as an import so they can manually merge in the defaults when necessary:

```js
const formsDefaults = require('./assets/css/plugins/forms').defaultTheme

module.exports = {
  theme: {
   extend: {
      forms: theme => ({
        formField: {
          default: {
            ...formsDefaults.formField.default,
            color: theme('colors.blue.500')
          }
        }
      })
    }
  },
  plugins: [
    require('./assets/css/plugins/forms')
  ]
}
```

This is what we recommend to people when trying to override a single color in the Tailwind docs already:

https://tailwindcss.com/docs/customizing-colors/#overriding-a-single-shade

**Comment by qntndev** [comment]
You raise a good point. In the end, not being able to override an entire nested key may add some downsides.
Thanks for the tips about exposing default configuration. Flattening the config structure with more explicit keys is the way I ended achieving it.
