### ISSUE TITLE
oppacity-75 

### ISSUE THREAD

**Issue by naschidaniel** [tailwindcss/tailwindcss#1363]
If the oppacity is set to 75%, a box will be displayed over all other elements. If the oppacity is set to 100% the box is behind all other elements (expected). The issue happens when i scroll on my page.

checkout the live perview www.milena-and-her-dog.com
![error_oppacity](https://user-images.githubusercontent.com/6561161/73874820-7d9b3d80-4854-11ea-988b-5682200ad51b.png)

thank you

**Comment by adamwathan** [comment]
This is just normal CSS behavior, opacity creates a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) so it sits above your header since your header has no z-index.

Give your header a z-index value higher than the z-index value of the cards (which are 0 by default) and it will be fixed 👍 Personally I'd probably use `z-30` as my default for a header, so there are still z-40 and z-50 for things like modal dialogs and z-10 and z-20 for other z-index concerns in the main page area that should still always sit below the header.
