### ISSUE TITLE
Consider moving accessibility to end of core plugins list for highest specificity

### ISSUE THREAD

**Issue by fiznool** [tailwindcss/tailwindcss#1432]
First of all let me extend my appreciation for this marvellous library. It's made me completely re-think the way that I build front ends.

I'm building a small countdown timer which, when the timer elapses, reveals  a 'Retry' button:

![2020-03-10 12 29 15](https://user-images.githubusercontent.com/820863/76312445-003b7080-62cb-11ea-99d4-1d79d66dd364.gif)

Since I'm (trying) to apply progressive enhancement techniques, I'd like this button to be visually hidden from sighted users until the timeout has elapsed, at which point the button will be visible. Screen readers, however, should probably 'see' the button even when the countdown is still occurring.

So, I am using the `.sr-only` class on the 'Retry' button to hide it visually. The problem is, the button also contains a bunch of other utility classes, including padding, margin, width and height. I'd like to preserve these classes so that the countdown timer JavaScript only needs to remove the `sr-only` class when it elapses. Unfortunately, since the `sr-only` class appears earlier in the generated CSS file than margin/padding/width/height classes, the visually hidden styles are not applied correctly (I end up with horizontal scrolling issues).

Would you consider a PR which moves the accessibiity plugin to the bottom of the `corePlugins` list, so anything in `sr-only` trumps any other utility classes applied? I'd consider this equivalent to the [current Bootstrap implementation](https://github.com/twbs/bootstrap/blob/a4a04cd9ec741050390746f8056cc79a9c04c8df/scss/mixins/_screen-reader.scss#L8-L18) which uses `!important` to ensure it has the highest specificity.

**Comment by adamwathan** [comment]
Hey! In your case I'd just wrap the button with an extra element and add the `sr-only` class to that so you can still just toggle the one class, unless I'm misunderstanding.

```html
<span class="sr-only">
  <button class="m-whatever w-whatever h-whatever p-whatever">...</button>
</span>
```

I'd like to keep the `sr-only` class early in the list specifically because it uses multiple properties. I recently needed to use `sr-only whitespace-pre-wrap` on a hidden textarea to override one of the `sr-only` properties for example, so sometimes the behavior is desirable. Since you can work around this with the wrapper element I think it's best to keep things the way they are 👍🏻

**Comment by fiznool** [comment]
Thank you Adam, I did not think of wrapping in a parent element! I'll go ahead and implement in this way.

🙏
