### ISSUE TITLE
Look for the config file in the project root by default

### ISSUE THREAD

**Issue by sebastiandedeyne** [tailwindcss/tailwindcss#144]
Would be nice if we wouldn't have to explicitly pass `./tailwind.js` to the plugin, and have it discover the file by itself if it uses the standard filename.

**Comment by adamwathan** [comment]
Right now passing no path actually uses the default Tailwind config, and I think it would be odd for that to behave differently based on the existence of a file.

I know that right now the docs recommend a `tailwind.js` file in the project root, but I'm considering changing this language because I think it's just as reasonable to keep that file with your CSS files, which would make having a default location a lot trickier.

**Comment by sebastiandedeyne** [comment]
Hmm I never really looked at it that way. I was thinking more of tools like babel where no config file actually means "nothing configured", not "default configuration".

Gonna close this for now, we'll see if it pops up again in the future :)
