### ISSUE TITLE
Multiple Same CSS Classes

### ISSUE THREAD

**Issue by jrock2004** [tailwindcss/tailwindcss#1452]
So I have the following element on a page that has 2 width defines. This happens because I want the ability for my component to pass in overrides to default CSS classes. 

```html
<input id="filter" class="w-full px-4 py-2 border rounded-sm focus:shadow-outline w-4/6" type="search">
```

Notice that is `w-full` and at the end there is `w-4/6`. Right now what is happening is w-full is overriding the other width.

I would expect that `w-4/6` would win because its defined after.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/655716/76785948-bbad4a80-678c-11ea-8465-c4278af8d942.png">

**Comment by benface** [comment]
The order of classes in the `class` attribute has no importance. What matters is [the order of the rules in the CSS](https://stackoverflow.com/questions/1321692/how-to-specify-the-order-of-css-classes) (assuming the rules have the same origin and specificity as is the case here), and `.w-full` is defined after `.w-4/6` so it takes precedence.

In terms of Tailwind, it is a bit confusing since doing the same thing with `@apply` instead of using classes in the HTML will work like you expect (the last utility defined takes precedence). But generally, you should not set two utilities that affect the same property on the same element since the result is not guaranteed.

**Comment by jrock2004** [comment]
If you do this in CSS 

```css
.input {
  width: 100%;
  padding: 15px;
  width: 150px;
}```
150px would overrule so not sure why this is not happening for tailwind. It should follow the allowed rules of CSS

**Comment by benface** [comment]
Please read the Stack Overflow question (and accepted answer) I linked to above. 👆

Tailwind does follow the "allowed rules of CSS", it is just CSS in the end so it has no choice but to.

**Comment by jrock2004** [comment]
Yeah I guess since tailwind does not take those classes and put it in css definition then for people who need flexibility to override defaults it out of luck. Thanks

**Comment by benface** [comment]
Related: https://github.com/tailwindcss/tailwindcss/issues/1446

**Comment by Nefcanto** [comment]
I also need this feature. I'm concatenating classes dynamically.

Here's a code sample from React + Tailwind:

```
// in Styles.js module
export const Button = "uppercase h-12 flex justify-center items-center bg-purple-700 ";

// in Pricing.js module
import { Button } from './Styles';

<button className={Button + " bg-green-400"}>Special offer</button>
```

I expect the background of special offer button to become green, but it does not.

The point is, when we concatenate classes in tailwind, the latter classes won't override the previous classes. This is far from the cascading nature of CSS.

**Comment by benface** [comment]
> This is far from the cascading nature of CSS.

That’s just how CSS is: the order of classes does not matter. Tailwind can’t do anything about it. A CSS-in-JS wrapper could, but that’s beyond the scope of Tailwind at this point I believe.

**Comment by RobinMalfait** [comment]
I usually don't recommend allowing to override styles via the className prop because this introduces a bunch of issues on is own.

Checkout these resources:
- https://gist.github.com/RobinMalfait/490a0560a7cfde985d435ad93f8094c5
- https://gist.github.com/RobinMalfait/7cf7a0498039027a1d591f5f2b908a95

**Comment by Nefcanto** [comment]
I just solved it using `!name` notation.

**Comment by deepakverma032002** [comment]
we can use tw-merge npm package for this, pls checkout it.
