### ISSUE TITLE
Interpolate theme in svg data uri?

### ISSUE THREAD

**Issue by simpel** [tailwindcss/tailwindcss#1457]
Hi all!

There is something I'm doing wrong in my SASS file. I'm trying to interpolate the theme() function in my svg data URI, but the code below gives me errors!

`background-image: url("data:image/svg+xml,%3Csvg width='1440' height='459' viewBox='0 0 1440 459' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1187.94 347.932C1105.19 337.701 999.24 308.031 941.402 177.418C904.548 94.0365 826.577 45.7811 764.643 24.8079C674.729 -7.41922 575.259 -4.86151 480.056 16.1117C413.003 30.9464 255.013 95.7416 102.311 54.3068C61.3636 42.8823 31.6764 25.1489 -0.399414 10.3142V458.254H1439.6C1416.06 435.917 1391.49 414.091 1359.41 395.846C1310.61 364.812 1269.33 357.821 1187.94 347.932Z' fill='#${theme('colors.primary')}'");
`

The result becomes:

`background-image: url(data:image/svg+xml,%3Csvg width='1440' height='459' viewBox='0 0 1440 459' …4.812 1269.33 357.821 1187.94 347.932Z' fill='#${theme('colors.primary')}');`

**Comment by danielkoek** [comment]
i think what you want to do is text-primary and fill-current instead of using the interpolate right?

**Comment by simpel** [comment]
yea but that has no effect on the background image...

**Comment by adamwathan** [comment]
We use [postcss-functions](https://github.com/andyjansson/postcss-functions) under the hood and it doesn't seem to support using functions inside of strings unfortunately.

I'd recommend asking a question/opening an issue there to see if anyone has any ideas 👍 

Personally I would consider writing this style using a Tailwind plugin instead of in your CSS file, then you would have access to proper JS interpolation:

```js
// tailwind.config.js
module.exports = {
  // ...
  plugins: [
    function ({ addComponents, theme }) {
      addComponents({
        '.my-class': {
          backgroundImage: `url("data:image/svg+xml,%3Csvg width='1440' height='459' viewBox='0 0 1440 459' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1187.94 347.932C1105.19 337.701 999.24 308.031 941.402 177.418C904.548 94.0365 826.577 45.7811 764.643 24.8079C674.729 -7.41922 575.259 -4.86151 480.056 16.1117C413.003 30.9464 255.013 95.7416 102.311 54.3068C61.3636 42.8823 31.6764 25.1489 -0.399414 10.3142V458.254H1439.6C1416.06 435.917 1391.49 414.091 1359.41 395.846C1310.61 364.812 1269.33 357.821 1187.94 347.932Z' fill='${theme('colors.primary')}'")`
        }
      })
    }
  ]
}
```

You could also try assigning it to a variable using [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) and referencing that variable, although not sure how to make that play nice on top of Sass.

Going to close because no plans to tackle this ourselves right now.
