### ISSUE TITLE
using tailwindcss + nextjs and alpinejs

### ISSUE THREAD

**Issue by mrzslr** [tailwindcss/tailwindcss#1539]
👋 Hey folks, I've been trying to use NextJS with Tailwindcss and AlpineJS together.
 In [Tailwind Heros](https://tailwindui.com/components/marketing/sections/heroes) examples, first example actually, shows that alpine imported via script tag but when wanna use NextJs and import even with turning off the SSR but still got `Unexpected token` which indicate `                      @click="open = true"` line. I get confused why It's not worked.

The way I use to turn off SSR in NextJS and import AplineJS : 
`export default dynamic(() => import('alpinejs')&& (Promise.resolve(IndexPage)),{
  ssr: false
})`

![image](https://user-images.githubusercontent.com/5070181/78689502-a5b62400-790b-11ea-9894-8aa687532123.png)

**Comment by adamwathan** [comment]
Hey! You should not use Alpine with Next.js, instead you should convert the component you want to use to a React component since Next is a React framework 👍 

Tailwind UI is meant to be an HTML-only, "bring-your-own-JavaScript" product (like the Bulma CSS framework for example). We only provide the Alpine examples to help people see what classes they need to toggle for the different states a component can be in. Like we mention in FAQ and documentation, the Alpine code is only included because we couldn't come up with a better way to document the classes that needed to be toggled using HTML comments or something:

https://www.notion.so/Tailwind-UI-Documentation-f9083ed0e2694690ac89253e88afb2b6#e0a33c88d378461ebde0d2074f34a084

There's some more good discussion about this here:

https://github.com/tailwindui/issues/issues/7#issuecomment-593134378

You are meant to implement any necessary interactive behavior yourself, using our barebones Alpine examples only to know what classes need to be toggled under which conditions.

So in your case you'd want to create any state you need using React's `useState` hook, then use standard React event listeners like `onClick` to manipulate that state.

**Comment by adamwathan** [comment]
Closing since this is actually a Tailwind UI support Q and not a Tailwind CSS thing 👍
