### ISSUE TITLE
purifycss-extended, a way to make Tailwind lighter?

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#157]
Hey @adamwathan,

As I said few days ago, I decided to fix some bugs on [purifycss/purifycss](https://github.com/purifycss/purifycss).
I forked the repo and made some fixes, now it's called [purifycss-extended](https://github.com/HapLifeMan/purifycss-extended).

Here's the result `before` and `after` (from `v1.3.2`):

<img width="589" alt="capture d ecran 2017-11-08 a 20 36 59" src="https://user-images.githubusercontent.com/1854141/32570709-434637a8-c4c5-11e7-8bad-0b5bae8de623.png">

Purification level is very outrageous and can be better.

But it means to rewrite the package from scratch or at least a lot of investment because `purifycss` read each input file and if you have a lot of text, each word will be added to the list of comparison. This list will be compared to CSS rules. It means that if you have `Hello World!` on your page, it will check for a `hello` and `world` class, and ever if you don't have these classes in your HTML/PHP/... files but they are present in your CSS, they'll stay here.

It's a good start and I'll see if I rewrite this code to be more accurate :)
Hope you'll use this package with Tailwind and maybe link it to the documentation!

**Comment by adamwathan** [comment]
Hey thanks for linking this @HapLifeMan! I'm going to close this as an actual issue because I don't think we would ever want to bake this directly into Tailwind, but I'm looking forward to testing this out when I have a chance.

Maybe open an issue over at https://github.com/tailwindcss/discuss if you'd like to have a discussion about using this package with anyone else who wants to give it a try 👍
