### ISSUE TITLE
Override text and background color

### ISSUE THREAD

**Issue by IL4Miy** [tailwindcss/tailwindcss#1579]
A text or backgroundcolor can be overwritten by another color, e.g.
`<div class="bg-gray-600 bg-red-500">` so the div is red
`<p class="text-gray-600 text-green-600">` so the text is green
However, this is not working with `text-white` and `text-black`.
So when I try this:
`<p class="text-gray-600 text-white">` the text is gray instead of white.

No huge problem but as a developer I would expect a similar behavior on all colors.

**Comment by tlgreg** [comment]
The order of class-names inside html doesn't change what is applied to an element. What matters is their specificity and the order in the css source code. These selectors have the same specificity, but the grays are declared after the white. That's why the text remains gray.
This is just how css and html works, not specific to tailwindcss.

If classes for the same property are changed dynamically then they should be swapped out instead.

**Comment by IL4Miy** [comment]
Solved
