### ISSUE TITLE
More cursor helpers

### ISSUE THREAD

**Issue by noamcore** [tailwindcss/tailwindcss#159]
There is a lot of cursor values to the `cursor` property, but just three in tailwindcss for now.

There is a reason to not put on the rest?

I can make a pull request if this issue is accepted.

**Comment by reinink** [comment]
I think this is mostly because the ones you most commonly use are `pointer` and `not-allowed`, plus we have `auto` to set it back to the browser default.

Adding all the options would simply add bloat to the framework, and not really add much extra value. Plus, it's trivial to [add new utilities](https://tailwindcss.com/docs/adding-new-utilities).

Are there any others you feel should be included by default?

**Comment by noamcore** [comment]
Well, for me it's pretty common using the `default`.

For example, to make panel headers feels more like a window inside the page.

Sometimes you want to make sure that user understand that he can't copy the text.

For me, at least, makes sense.

**Comment by reinink** [comment]
Yep, fair enough, I could see adding that one.

@adamwathan What do you think?

**Comment by adamwathan** [comment]
> Sometimes you want to make sure that user understand that he can't copy the text.

@noamcore A better way to handle that scenario is to use the `select-none` utility which sets `user-select: none` and also happens to change the cursor:

https://jsfiddle.net/pvbwdLsp/4/

Going to close this for now; happy to revisit if there's a strong argument for shipping more cursors by default.

**Comment by adamwathan** [comment]
Turns out Safari doesn't change the cursor which is lame. We'll add `default` 👍

**Comment by MichaelDeBoey** [comment]
@adamwathan When I try the JSFiddle in Chrome (61.0), I also see the `text` cursor.
