### ISSUE TITLE
Error after updating from 1.2.0 to 1.3.4

### ISSUE THREAD

**Issue by boboldehampsink** [tailwindcss/tailwindcss#1603]
Hi, after updating from 1.2.0 to 1.3.x I see the following error on webpack build:

```
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 0 !important * calc(1 - var(--space-y-reverse))
^....^
    at /app/main.c57d78fe076e25d4deee.css:3551:3
    at Object.parseError (/app/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (/app/node_modules/postcss-calc/dist/parser.js:2333:44)
    at Object.lexer_next [as next] (/app/node_modules/postcss-calc/dist/parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (/app/node_modules/postcss-calc/dist/parser.js:3403:18)
    at fastLex (/app/node_modules/postcss-calc/dist/parser.js:1603:27)
    at Parser.parse (/app/node_modules/postcss-calc/dist/parser.js:1677:30)
    at /app/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/app/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/app/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/app/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/app/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at /app/node_modules/postcss-calc/dist/index.js:27:32
    at /app/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/app/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/app/node_modules/postcss/lib/container.js:131:17)
    at /app/node_modules/postcss/lib/container.js:148:24
    at Root.each (/app/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/app/node_modules/postcss/lib/container.js:131:17)
    at /app/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/app/node_modules/cssnano/dist/index.js:31:51)
```

Waited out a few Tailwind updates but it still happens on 1.3.4

**Comment by philippbosch** [comment]
This looks like you have an `!imporant` in your tailwind spacing config. Something along these lines:

```js
module.exports = {
  theme: {
    extend: {
      spacing: {
        '0': '0 !important',
      }
    }
  }
}
```

And then when `0 !important` is used for `size` here https://github.com/tailwindcss/tailwindcss/blob/5b3f8b5461a4e2a0a7eb6169985d37581f609ad5/src/plugins/space.js#L10 the resulting CSS is invalid because `!important` may only appear at the end of a declaration.

IMO using `!important` in spacing values in your config is not supported. There's probably a better way to achieve what you are trying to achieve with setting it up like this in the first place. If you provide some details on your use case I'll try to help.

**Comment by tlgreg** [comment]
Tailwind supports a global option to add `!important` to every utility.
https://tailwindcss.com/docs/configuration#important

Otherwise, there are a few plugins around that support it through variants.
https://www.npmjs.com/package/@neojp/tailwindcss-important-variant
https://www.npmjs.com/package/tailwindcss-important

**Comment by boboldehampsink** [comment]
Ok fair, but what if you want to use `margin: auto` for example? Seeing this:

```
  Erroneous area:
1: auto * calc(1 - var(--space-y-reverse))
^..^
```

**Comment by philippbosch** [comment]
For `margin: auto` you would use the `m-auto` utility class. For this to work you don‘t need to put `auto` in your `spacing` config.

**Comment by boboldehampsink** [comment]
Thanks

**Comment by philippbosch** [comment]
Sure. Could you please close the issue? Thanks

**Comment by violoncelloCH** [comment]
hi, thanks for this great framework!
I've a `max-content` in my `spacing` config and I'm getting pretty much the same error now since `v1.3.0`... It seems this is not the intended way to use the tailwind config; what would be the recommended way in this case? To just manually create the corresponding class?

**Comment by philippbosch** [comment]
You can always do that. Or create a plugin that generates the utility classes you need. 

I‘m not familiar with `max-content`. How do you use it with tailwind? Can you give an example?

**Comment by violoncelloCH** [comment]
okay thanks for your response!
I use it for a (rather small) element with text (two words) in it which I don't want to be (line)broken; `width: max-content` sets the with to the with of the contained text without a linebreak being introduced in the text...
by adding
```
      spacing: {
        'maxcontent': 'max-content',
      }
```
into my extending tailwind config I was able to apply this by using the `w-maxcontent` class with tailwind < 1.3.0...

**Comment by bhoomit-ganatra** [comment]
> Ok fair, but what if you want to use `margin: auto` for example? Seeing this:
> 
> ```
>   Erroneous area:
> 1: auto * calc(1 - var(--space-y-reverse))
> ^..^
> ```

can you please tell me how do you solve it I am not getting
