### ISSUE TITLE
Tailwind 1.4.x breaks social media cards

### ISSUE THREAD

**Issue by danspratling** [tailwindcss/tailwindcss#1737]
**Issue:**
I noticed this issue after an improvement I made to my personal site. After upgrading to v1.4.4 my social media sharing cards were no longer working. It took me a while to debug as it's not initially clear what is causing the issue. The site does not error locally, builds correctly, and does not appear broken on deploy - it is only social media cards which are broken.

**Issue version: 1.4.x
Last known safe version: 1.2.0
My site setup: Gatsby, Contentful & Tailwind.**

I'm not sure if this is just an issue with SSG's (and any other Critical CSS approaches as they pull CSS into the head). It is probably not an issue with Gatsby's implementation of Tailwind due to version 1.2.0 working as expected. It's not clear exactly what is causing this issue, but it appears when upgrading versions without making any other changes.

**How to test:**
Open up any site using tailwind 1.4.x site (the site I used is [here](https://serene-swartz-6e587b.netlify.app/)).
[Open up the opengraph debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fserene-swartz-6e587b.netlify.app%2F)
Add the URL and scrape the site to fetch new information

**Comment by adamwathan** [comment]
That appears to be pulling in a _lot_ more than just the critical CSS for your site, it seems like almost every class in the `head` is not even present on your page.

I suspect the root cause is maybe the page being too large because of all the unnecessary inlined CSS and sites pulling the cards are giving up on streaming the content after a certain size limit.

I would be looking at how you've got Critical CSS configured, because it appears to be misconfigured as far as I can tell.

Just as an example, not a single one of these classes is actually used on your site, let alone critical:

![image](https://user-images.githubusercontent.com/4323180/81426383-1c228d80-9127-11ea-91dd-abc8e62fec07.png)

**Comment by danspratling** [comment]
Looks like my gatsby purgecss config wasn't specific enough, and tailwind 1.4.x must have a lot of extra generated styles leading to the issue. For the record, this is Gatsby's default approach, i haven't changed anything.

Before - 50% reduction
```js{6}
{
  resolve: `gatsby-plugin-purgecss`,
  options: {
    printRejected: true,
    tailwind: true,
    ignore: ['src/scss', '/react-carousel/', '/prismjs/'],
  },
},
```

After - 98% reduction
```js{6}
{
  resolve: `gatsby-plugin-purgecss`,
  options: {
    printRejected: true,
    tailwind: true,
    ignore: ['./src/scss', '/react-carousel/', '/prismjs/'],
  },
},
```

**Comment by danspratling** [comment]
Yep, just updated, and that's fixed the issue.
