### ISSUE TITLE
[FeatureRequest] use css in js to generate css in runtime

### ISSUE THREAD

**Issue by xialvjun** [tailwindcss/tailwindcss#1852]
We have classes like `h-16`, `w-16`. To offer enough classes, we need to generate many classes like `h-16` even at many time we don't use it. So why not generate it at runtime? 

```jsx
import { style } from 'typestyle;
import classname from 'classname';

const h = (n:number) => style({ height: n });
const w = (n:number) => style({ width: n });

<div className={classname(h(16), w(16))}></div>
```

https://github.com/typestyle/typestyle

**Comment by adamwathan** [comment]
This is something we'd like to tackle in an official capacity in the future, but probably as a separate project. Going to close because not a lot of benefit to leaving it open, since it is already something that's on our roadmap to explore.

In the mean time I would check out twin.macro:

https://github.com/ben-rogerson/twin.macro
