### ISSUE TITLE
Tailwind occasionally implements not (quite) supported browser features

### ISSUE THREAD

**Issue by danspratling** [tailwindcss/tailwindcss#1885]
I've noticed a couple of times with some tailwind features that they're not working as expected in the current version of TailwindCSS.

A current (1.4.5) example of this is `appearance-none`

Current
```
appearance: none;
```

Previous
```
-webkit-appearance: none !important;
-moz-appearance: none !important;
appearance: none !important;
```

However the current version of chrome is still 83, which *does not yet support dropping the -webkit- prefix*
https://caniuse.com/#search=appearance

I've noticed this on occasion with features being updated eagerly. Is there any reason behind this?

Note: I love that you're keeping up with browser changes and consistently keeping Tailwind modern! It can just be a slight pain when you beat the browser to market and temporary fixes, or a rollback in version is required until the new browser version releases.

**Comment by adamwathan** [comment]
Nothing has changed in this regard, you just need to make sure you use a tool like `autoprefixer` to add any missing vendor prefixes 👍 

We've never built that in by default, even since version 0.1.0.

Our CDN builds always have it enabled though, like you can see here:

![image](https://user-images.githubusercontent.com/4323180/83929652-25247000-a762-11ea-8cfa-026d16b2812b.png)

![image](https://user-images.githubusercontent.com/4323180/83929671-3b323080-a762-11ea-8885-21d300969965.png)

**Comment by estevanmaito** [comment]
Can you point out the source for your _previous_ example of `appearance`?

Because it's been like this since 1.0 [ a0de7e0 on 14 Jan 2019 ](https://github.com/tailwindcss/tailwindcss/blob/a0de7e096309dffad60b9590712eafeadac194df/src/plugins/appearance.js)

Also, the documentation is clear about prefixes: Tailwind doesn't automatically add vendor prefixes to any of its styles https://tailwindcss.com/docs/browser-support/#vendor-prefixes

**Comment by danspratling** [comment]
Sounds like this is clearly a mistaken pattern I was seeing. I've been using tailwind without autoprefixer on a few projects and not run into this problem very much (just a couple times).

Every time I've run into the issue, the browsers have been on the verge of removing the prefixes so I assumed that Tailwind was just ahead of the curve.

Suggestion: 
As @estevanmaito mentions the docs are clear on the use of prefixes, but this isn't clear within the installation instructions https://tailwindcss.com/docs/installation/#using-tailwind-with-postcss. It's not mentioned that this is the case, you have to go looking for browser support. 

A single line could be added to the installation instructions to reinforce the use of autoprefixer in case the user is unfamiliar with it, they're following another guide for tailwind installation alongside these docs, or just accidentally skipped over it in the code example.
