### ISSUE TITLE
[Feature Proposal] Consider adding option to enable all variants

### ISSUE THREAD

**Issue by carlos-duran** [tailwindcss/tailwindcss#1911]
Since we have PurgeCSS inside Tailwind, most of us don't need to worry about bundle size. So if we have an option for enabling all variants could make the config cleaner, something like:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants: {
    all: true
  },
}
```

I know that order matters, so the default extended config could be created with the most common use cases and, if the user wants a different behavior, he/she could do it as always:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants:{
    all: true,
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover', 'disabled'],
  },
}
```

Regards!

**Comment by adamwathan** [comment]
Right now you can do this which probably solves your problem:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants: ['responsive', 'hover', 'focus', 'group-hover', 'disabled'],
}
```

It apples that same list of variants to every single utility.

We used to have an `all` feature but when we made it possible for plugins to add variants it became a lot less useful because we had no idea what order to put your variants in when they included plugin variants. The global array syntax solves this problem but is a little more work than adding `all`. 

No plans to add this back right now unfortunately, hopefully the array syntax is at least an improvement for you.

**Comment by UltraCakeBakery** [comment]
> Right now you can do this which probably solves your problem:
> 
> ```js
> // tailwind.config.js
> module.exports = {
>   // ...
>   variants: ['responsive', 'hover', 'focus', 'group-hover', 'disabled'],
> }
> ```
> 
> It apples that same list of variants to every single utility.
> 
> We used to have an `all` feature but when we made it possible for plugins to add variants it became a lot less useful because we had no idea what order to put your variants in when they included plugin variants. The global array syntax solves this problem but is a little more work than adding `all`.
> 
> No plans to add this back right now unfortunately, hopefully the array syntax is at least an improvement for you.

For me this does not work anymore since upgrading to tailwind 2.0 (nuxt-tailwind 4.0.1). Is this correct? If so, is there a alternative? @tailwindcss/jit is not an option as it is still very unstable in our testing.
