### ISSUE TITLE
Setting border-width to 0 causes margin collapse

### ISSUE THREAD

**Issue by jmhungdev** [tailwindcss/tailwindcss#1950]
I was struggling with a seemingly bug in css, but turned out to be  a known thing called the margin collapse. Here's a [demo](https://cdpn.io/jmhungdev/debug/eYJWzGd/dGrXWKPXeDjM) in code pen.

If you use Chrome like me, you can see the body element is being pushed down by 10px from top margin by its child element `<div>`. This is known as the margin collapse in css, as browser takes the larger margin of two adjacent elements with no borders.

It makes you wonder if setting border-width to 0 is a good default. If I don't manually set border on each element I create, I bound to encounter issues with margin collapse.

**Comment by estevanmaito** [comment]
The pen gives this error: This debug view expired.

Are you trying to share a PRO only pen?

**Comment by jmhungdev** [comment]
@estevanmaito  that's weird, I just tested again using incognito mode, and it worked. I don't have a PRO account on codepen.

**Comment by adamwathan** [comment]
Hey @jmhungdev! What you're seeing is just standard CSS behavior:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

This is the case whether or not we set a default border-width of 0, because elements have a border-style of "none" by default otherwise which results in the same margin collapsing by default either way. So even if we got rid of that default you'd see the exact same result.
