### ISSUE TITLE
Not purging vue css block

### ISSUE THREAD

**Issue by tzsk** [tailwindcss/tailwindcss#1974]
I'm facing a weird issue with tailwind purgeCss. It successfully purges any unused classes from external `.css` or `.scss` files. But it is not purging any classes defined inside the `<style>` block.

### Postcss Config: ./postcss.config.js
```js
module.exports = {
  plugins: [require("tailwindcss"), require("autoprefixer")]
};
```

### Tailwind Config: ./tailwind.config.js
```js
module.exports = {
  purge: {
    enabled: true,
    mode: "all",
    content: ["./public/**/*.html", "./src/**/*.vue"]
  },
  theme: {
    extend: {}
  },
  variants: {},
  plugins: []
};
```

### App Component: ./src/App.vue
```vue
<template>
  <div>
    <div>
      <router-link to="/">Home</router-link> |
    </div>
    <router-view />
  </div>
</template>

<style lang="scss" src="@/assets/app.scss"></style>

```

### Home Component: ./src/views/Home.vue
```vue
<template>
  <div>
    <h1 class="being-used">This is home page</h1>
  </div>
</template>

<style lang="scss" scoped>
.being-used {
  @apply text-teal-700;
}
.not-being-used {
  @apply text-purple-700;
}
</style>
```

 In the above example event when I'm running the app on `--mode=production` I can still see the class `.not-being-used` in the css chunk file.

But, when I'm extracting the style block to a separate `./assets/views/home.scss` file. And pointing to it in the Home Component it successfully purges the class `.not-being-used`

### Home Component: ./src/views/Home.vue - Working
```vue
<template>
  <div>
    <h1 class="being-used">This is home page</h1>
  </div>
</template>

<style lang="scss" scoped src="@/assets/views/home.scss"></style>
```

### Home SCSS: ./src/assets/views/home.scss
```scss
.being-used {
  @apply text-teal-700;
}
.not-being-used {
  @apply text-purple-700;
}
```

Just in case if you wanna look at `app.scss`

### App SCSS: ./src/assets/app.scss
```scss
@tailwind base;

@tailwind components;

@tailwind utilities;
```

This should not behave like this and also tried looking up the issue but couldn't find any single instance of this issue. So that leads me to believe I'm doing something wrong. But don't know what. If someone can please point me to the right direction.

**Comment by adamwathan** [comment]
Can you create a Vue project that reproduces this issue and provide a link to it so I can troubleshoot more easily? Unfortunately don't have time right now to set up a project like this completely from scratch.

**Comment by tzsk** [comment]
@adamwathan Of course, coming right up.

**Comment by tzsk** [comment]
@adamwathan Here is the sample Vue-CLI project. https://github.com/tzsk/tailwind-demo

#### I'm also attaching a screenshot for reference and a quick look at the problem.


![image](https://user-images.githubusercontent.com/13273787/85939803-f307c780-b935-11ea-8afd-1ff6fe5c8aab.png)

**Comment by tzsk** [comment]
@adamwathan I guess it's a bug. Have been asking a in a couple of forums and they're also facing the same issue.

**Comment by adamwathan** [comment]
So the reason this happens is because of how PurgeCSS works. All it does is scan your template files looking for things that match a certain regex, and if it finds them it keeps them.

So in your case, you are telling PurgeCSS to scan anything with a `*.vue` extension, which means it is scanning this whole file:

```vue
<template>
  <div>
    <h1 class="being-used">This is home page</h1>
  </div>
</template>

<style lang="scss" scoped>
.being-used {
  @apply text-teal-700;
}
.not-being-used {
  @apply text-purple-700;
}
</style>
```

PurgeCSS sees the string `not-being-used` and determines it _is_ being used, since it found it in the file. It has no idea that it was present in a CSS block rather than a template block, because it doesn't have any complex parsing logic or anything to try and differentiate, again it's just a super simple regex check.

If you wanted to make it more sophisticated you could write a [custom extractor](https://purgecss.com/extractors.html#creating-an-extractor) for `*.vue` files that only searches the `template` and `script` portions of your Vue files and ignores any strings present in the `style` block.
