### ISSUE TITLE
Official Plugins Not Purging

### ISSUE THREAD

**Issue by mattwaler** [tailwindcss/tailwindcss#2052]
### Describe the problem: 

Official plugins like custom forms and typography are not purged properly, and all styles make it into production builds.

### Link to a minimal reproduction:

https://github.com/mattwaler/new-site

Check the config file, and run `npm run build` in this repo and inspect `dist/assets/main.bundle.css`, you can see that ALL of the form and typography classes survived the purge despite most not being used.

**Comment by sanscheese** [comment]
For this you'll need to purge at the components layer. Though will need to be careful to not over purge as often the typography plugin will be used for content not necessarily in the codebase.

Another option to lower the size of the typography output is disable any of the size modifiers you may not be using.

**Comment by adamwathan** [comment]
This is by design and outlined in the documentation here:

https://tailwindcss.com/docs/controlling-file-size/#removing-all-unused-styles

The documentation contains instructions for purging _all_ styles if that's what you'd prefer 👍

**Comment by pluma** [comment]
I'm not sure this is really by design or maybe I just misunderstand `mode: all`:

> be very careful to provide the paths to all files that might reference any classes or HTML elements

The size modifiers and variants for typography are very useful, so for example I want `xl:prose-lg` but this means by default I will also get all the unused combinations like `sm:prose-2xl` even though I'm not using them.

Because the `prose` variants often apply to dynamic content, I believe that using `mode: all` would result in too much purging.

It's also confusing that the explanation is immediately followed up by this:

> We do not recommend this, and generally find you get 99% of the file size benefits by sticking with the more conservative default approach.

Is there a way to limit typography to only certain size/variant combinations? Otherwise this would really be something I'd expect to be picked up by purging.

**Comment by adamwathan** [comment]
I would recommend using `mode: all` and whitelisting all of the regular HTML elements that appear in prose content.

You can also disable size modifiers and responsive variants in the configuration:

https://github.com/tailwindlabs/tailwindcss-typography#disabling-size-modifiers

**Comment by pluma** [comment]
@adamwathan: I'll try going the `mode: all` route with a safelist but I still think there should be a better way given the massive caveats of that solution (i.e. it's a massive footgun, which is why the documentation rightfully recommends it only as a last resort).

Just to be clear: I want size modifiers and I want responsive variants. But I only want some of the combinations, not all of them. E.g. I want `xl:prose-lg` and I want `sm:prose` but I don't want `xl:prose` and `sm:prose-lg`. So even if it was possible to restrict the plugin to _certain_ responsive variants and if I explicitly safelist specific sizes, I'd still end up with more useless variations than ones I actually use (without going the `mode: all` route).

**Comment by adamwathan** [comment]
I don't think there are really massive caveats, you just need to understand the tools a little more deeply to use the `all` option which isn't a burden we wanted to put on people by default. We use the `all` option for all of our own projects for what it's worth.

I would definitely recommend using `mode: 'all'` if you want the smallest CSS size and just learning how to steer PurgeCSS a little more manually. It's not a "last resort". We'll likely change the defaults in Tailwind 2.0 to purge everything honestly. The only real foot-gun is if your content doesn't actually contain tags like `p`, `h2`, etc. because you are scanning markdown templates instead of HTML templates. We work around that ourselves by writing a custom extractor for markdown files that compiles the markdown before scanning it:

https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/tailwind.config.js#L13

**Comment by pluma** [comment]
Thanks, that makes sense to me. I think if there were an easy way to tell PurgeCSS to whitelist all HTML elements (i.e. only purge on IDs and classes) that would make things a lot easier (and safer) without the need to change how components/plugins work or are purged.

**Comment by adamwathan** [comment]
That's a good idea and something we could actually build in to Tailwind itself pretty easily 👍
