### ISSUE TITLE
Problem when building components

### ISSUE THREAD

**Issue by BostjanOb** [tailwindcss/tailwindcss#221]
Hi

I was recently working with tailwind and hit some problems when building components.

So for example let’s take a contact card from the documentation:
```html
<div class="bg-white mx-auto max-w-sm shadow-lg rounded-lg overflow-hidden px-6 py-4">
	<div class="sm:flex sm:items-center ">
		<div class="text-center sm:text-left sm:flex-grow">
			<div class="mb-4">
				<p class="text-xl leading-tight">Bostjan</p>
				<p class="text-sm leading-tight text-grey-dark">Developer</p>
			</div>
			<div>
				<button class="text-xs font-semibold rounded-full px-4 py-1 leading-normal bg-white border border-purple text-purple hover:bg-purple hover:text-white">Message</button>
			</div>
		</div>
	</div>
</div>
```

If we have a lot of contact cards it would make sense to make a component and export the repeating classes:

SCSS:
```css
.card {
	@apply .bg-white .mx-auto .max-w-sm .shadow-lg .rounded-lg .overflow-hidden .px-6 .py-4;

	
	button {
		@apply .text-xs .font-semibold .rounded-full .px-4 .py-1 .leading-normal .bg-white .border .border-purple .text-purple;

		&:hover {
			@apply .bg-purple .text-white;
		}
	}
}
```

HTML:
```html
<div class="card">
	<div class="sm:flex sm:items-center"></div>
		<div class="text-center sm:text-left sm:flex-grow">
			<div class="mb-4">
				<p class="text-xl leading-tight">Bostjan</p>
				<p class="text-sm leading-tight text-grey-dark">Developer</p>
			</div>
			<div>
				<button>Message</button>
			</div>
		</div>
	</div>
</div>
```

Now .... let assume we want to make another card but we want the button to be blue. So we add `.bg-blue` to the button as the utility class. But this won’t work because the CSS selector from the component is more important than the utility class.

I was hoping that setting important to true would fix this problem, but that option applies to all the utilities used with `@apply` too.

Would it be better to make !important in `@apply` optional and make it so it should be specified together with `@apply`.

For example:
```
@apply .border .mx-2 !important;
```

or use custom:
```
@apply .border;
@apply-important mx-2;
```

Regards,
Bostjan

**Comment by adamwathan** [comment]
Hey Bostjan! That's an interesting idea and maybe something we can think about adding. We did have an idea for an `@important` directive for a short period of time but ended up dropping it:

```css
@important {
  @apply .mx-2;
}
```

I would say in general though your problem is better solved by not relying on descendant selectors when doing component styling like this if you can avoid it.

I'd personally make the button a completely separate component, since it's likely that you are going to want to use that same button style in other places besides cards:

```scss
.card {
    @apply .bg-white .mx-auto .max-w-sm .shadow-lg .rounded-lg .overflow-hidden .px-6 .py-4;
}

.button-purple {
    @apply .text-xs .font-semibold .rounded-full .px-4 .py-1 .leading-normal .bg-white .border .border-purple .text-purple;
    &:hover {
        @apply .bg-purple .text-white;
    }
}
```

Then I'd write the HTML like this:

```html
<div class="card">
    <div class="sm:flex sm:items-center"></div>
        <div class="text-center sm:text-left sm:flex-grow">
            <div class="mb-4">
                <p class="text-xl leading-tight">Bostjan</p>
                <p class="text-sm leading-tight text-grey-dark">Developer</p>
            </div>
            <div>
                <button class="button-purple">Message</button>
            </div>
        </div>
    </div>
</div>
```

If your actual component is more coupled than that and composing the UI out of separate components like that doesn't feel right, I'd still take more of a BEM-ish approach where you give the child element it's own class and avoid using a descendant selector so you can keep the specificity low:

```
.card {
    @apply .bg-white .mx-auto .max-w-sm .shadow-lg .rounded-lg .overflow-hidden .px-6 .py-4;
}
.card-button {
    @apply .text-xs .font-semibold .rounded-full .px-4 .py-1 .leading-normal .bg-white .border .border-purple .text-purple;
    &:hover {
        @apply .bg-purple .text-white;
    }
}
```

Hope that helps!

If you're interested, I wrote a big blog post a while back that talks about how I usually decompose these sorts of things, maybe it'll be a cool read:

https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

**Comment by BostjanOb** [comment]
Thanks for the suggestion. That was exactly what I did after I gave up on !important :)
I just wanted to point out what kind of problems can occur when building a similar component.
