### ISSUE TITLE
Why not include all of SUIT CSS Base in preflight?

### ISSUE THREAD

**Issue by benface** [tailwindcss/tailwindcss#224]
I am curious as to what the reasoning was for only including [SUIT CSS Base](https://github.com/suitcss/base) partially in preflight? The following rules are missing:

```
button {
  border: 0;
}

fieldset {
  border: 0;
}

iframe {
  border: 0;
}

ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

I feel like including the whole thing would be better for the following reasons:
- I don't see any reason to use the user agent's default border on `button`, `fieldset`, and `iframe` when it's so easy to add a border to any element on demand with Tailwind (and then you control the width and color).
- We remove the default `margin` on `h1`-`h6`, `p`, and a bunch of other elements, so why not `ol` and `ul` as well? It feels odd to have to do it manually every time.
- As for `list-style: none;`, I don't really care about that one, especially since you can easily remove the default appearance of a list by setting the `display` on `li` elements. Still, if it's the only rule you're gonna remove, why not keep them all and replace the `list-reset` utility by `list-style-*` utilities? (`list-style-circle`, `list-style-square`, etc.)

**Comment by adamwathan** [comment]
@benface Those changes were made because the declarations in SUIT broke our border utilities.

`border: 0` sets these styles:

```
border-width: 0;
border-style: none;
border-color: currentColor;
```

That means that adding our `.border` class which only sets `border-width: 1px` doesn't actually enable a border if the element has previously had it's border-style set to `none`.

We have these styles in our reset which accomplishes the same goal of resetting border styles but without using the border shorthand property, so we can still default the border style to `solid`:

```
*,
*::before,
*::after {
  border-width: 0;
  border-style: solid;
  border-color: config('borderColors.default', currentColor);
}
```

We are not using the user agent's default border; we are setting carefully crafted default border settings on every element in the browser to ensure that adding `.border` to an element works properly.

We don't remove the margin, padding, or list style type on lists because it is impossible to bring back the browser's default list style behavior if you undo it in a reset.

This is why we have the `.list-reset` class to reset the margin, padding, and list style on any lists that you don't want to look like normal lists:

https://tailwindcss.com/docs/lists

**Comment by benface** [comment]
Hey @adamwathan thank you, I missed that about the border! However for the `ul` and `ol`, you could say the same about the default margin of headings and paragraphs, no?

**Comment by reinink** [comment]
@benface You could, but reapplying the default browser styles for lists is actually really difficult. We battled this decision for quite some time, and in the end felt this was the best approach, especially considering how easy it is for you to reset list styles in your own project. In fact, that's what I prefer in my projects as well, here is how I do it:

```css
ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

Hope that helps! 👍

**Comment by adamwathan** [comment]
We could probably remove the top/bottom margin on lists by default actually, but not the padding because the padding is necessary for list bullets to show up in the right place. I'd have to test in a bunch of browsers and make sure.

**Comment by benface** [comment]
That would be great and consistent in my opinion. But if not I’ll simply do like @reinink does, no big deal at all. Thank you!
