### ISSUE TITLE
Font-family declaration breaks with numbers

### ISSUE THREAD

**Issue by sebastiandedeyne** [tailwindcss/tailwindcss#252]
I have a font-family with a number in it, and that breaks the declaration because the fonts aren't wrapped in quotes.

This breaks:

<img width="359" alt="screen shot 2017-11-28 at 09 43 42" src="https://user-images.githubusercontent.com/1561079/33310117-cb897890-d420-11e7-89df-e5240097de0c.png">

Without the number, it works (but that's not my font, so no solution):

<img width="359" alt="screen shot 2017-11-28 at 09 45 07" src="https://user-images.githubusercontent.com/1561079/33310138-dd44d0ca-d420-11e7-9dcb-a20dfbafcfc1.png">

Quotes would fix it though:

<img width="356" alt="screen shot 2017-11-28 at 09 45 43" src="https://user-images.githubusercontent.com/1561079/33310150-ed2a6888-d420-11e7-908c-4beb08f0a627.png">

**Comment by adamwathan** [comment]
Hey @sebastiandedeyne! Yeah this is something we considered early on, and considered trying to handle in a magical way, but the rules for when you need quotes around a font are actually [quite complex](https://mathiasbynens.be/notes/unquoted-font-family), so instead of spending time trying to solve that in a robust way, we figured it's much easier to just tell people to add quotes if they need quotes.

So in your case, write your config like this:

```
fonts: {
  sans: ['"DIN 2014"', ...],
  // ...
}
```

We might make this more automagical down the road, but for now to keep things simple, the rule is "if you're values need quotes, add quotes."

**Comment by sebastiandedeyne** [comment]
Makes sense, that's how I solved it for now :)

But why not do it the other way around, and always add quotes?

**Comment by adamwathan** [comment]
> But why not do it the other way around, and always add quotes?

That would break certain keywords like `serif`, `sans-serif`, etc.

We could whitelist those for sure but just seemed like unnecessary magic when we had so much other work to do.

**Comment by sebastiandedeyne** [comment]
Cool, gonna leave the quotes in my config then, thanks 😄
