### ISSUE TITLE
Layout debug

### ISSUE THREAD

**Issue by SteveALee** [tailwindcss/tailwindcss#284]
Tachyons has a layout debug feature that shows the borders of elements in various colours.

This can be very useful and I wonder if such an option would be in scope for tailwind?

**Comment by adamwathan** [comment]
Hey @SteveALee! No plans to bake this into Tailwind any time soon, but you could always take the Tachyons styles and add those to your own project in a place that's easy to comment and uncomment when needed like they suggest.

To me this seems like something better solved by a browser extensions that you could toggle on and off on any website instead of baking it into a stylesheet.

Cheers!

**Comment by SteveALee** [comment]
I agree re debug tooling. Thanks for confirming what I expected :)
