### ISSUE TITLE
Modern alert with Badge breaks on IE 11

### ISSUE THREAD

**Issue by ekrist1** [tailwindcss/tailwindcss#287]
The Modern alert with badge breaks on IE 11:
https://tailwindcss.com/docs/examples/alerts#modern-with-badge
![badge](https://user-images.githubusercontent.com/8544305/33543315-d649b64a-d8d6-11e7-886b-82cf5a8f3e3d.png)

A workaround is to set a fixed width on the "p-2 bg-indigo-darker..." class. Is there a better way to solve this compability issue?

**Comment by tlgreg** [comment]
The issue here is `.flex-1`, which is shorthand for:
`flex-grow: 1`
`flex-shrink: 1`
`flex-basis: 0` (% in most prowesers, px in IE)

In IE11 `flex-basis` is basicly beats `flex-grow` with wrappable text.

The purpose here is that the little arrow stays at the right edge on smaller screens too, which should also work with `.flex-grow` instead of `.flex-1`
