### ISSUE TITLE
Does tailwinf require autoprefixer?

### ISSUE THREAD

**Issue by SteveALee** [tailwindcss/tailwindcss#291]
The config examples in https://tailwindcss.com/docs/installation all include autoprefixer. is this just for example or does tailwind have a dependency on it? Other than installing it configure postcss?

**Comment by adamwathan** [comment]
Tailwind doesn't require it to work per-se, but you probably want to add it to your project regardless, otherwise certain utilities that set properties that don't exist without vendor prefixes (like `appearance-none`) wouldn't work.

We include it in the installation/configuration examples just to help set the context better, and to implicitly inform people that if using autoprefixer (like most projects are), that Tailwind should run *before* it, and not after it.
