### ISSUE TITLE
.mx-auto missing in latest version?

### ISSUE THREAD

**Issue by ryanscherler** [tailwindcss/tailwindcss#294]
I updated tailwind to 0.3.0 and it seems to be missing the .mx-auto (container centering) class? Has anyone else experienced this oddity?

**Comment by adamwathan** [comment]
Hey @ryanscherler, it sounds like you are updating from 0.1.x straight to 0.3.0.

One of the changes in 0.2 was moving `auto` to the default margin configuration instead of being a hard-coded value:

https://github.com/tailwindcss/tailwindcss/releases#auto-is-no-longer-a-hard-coded-margin-value

You just need to update your config file to include `auto` like the latest default config file does:

https://github.com/tailwindcss/tailwindcss/blob/master/defaultConfig.stub.js#L634-L659

**Comment by ryanscherler** [comment]
This makes total sense, thanks @adamwathan
