### ISSUE TITLE
Grid creates horizontal scrolling

### ISSUE THREAD

**Issue by uikid** [tailwindcss/tailwindcss#295]
Hello,

if creating a grid like the docs say, I get horizontal scrolling.

Example: https://codepen.io/anon/pen/ZaNXMw

You have to resize the window to a breakpoint of the container or for example 999px, then there is the horizontal scrolling.

Am I doing something wrong?

**Comment by adamwathan** [comment]
Hey @uikid! Add `px-8` to your `container` div to make up for the negative margin and it should fix your issue.

What's happening is the container has a max width of x pixels, and because the row has negative margin, it's width is (x + negative margin), causing it to overflow it's container and trigger scolling.

Adding padding to the parent container that's equal to the negative margin makes sure there's room for that negative margin to occur without blowing out the parent container.

I'll update the example to include this, thanks!

**Comment by uikid** [comment]
Thank you.

That means the container or parent element must have a padding the same size as the negative margin. Is that correct?

Tailwind looks great so far, I like the simple docs. Thank you very much!

**Comment by adamwathan** [comment]
Yep you got it!

**Comment by adamwathan** [comment]
Alternatively you could add `overflow-hidden` to the `container` div as well, just depends on what your trying to achieve with the final design.

**Comment by uikid** [comment]
The padding on the container works fine for me. For other cases where I need different padding, I will user overflow-hidden.

Thank you.
