### ISSUE TITLE
[Feature Request] Dropdown

### ISSUE THREAD

**Issue by marktopper** [tailwindcss/tailwindcss#301]
I would like to request having a dropdown like this: http://getbootstrap.com/docs/4.0/components/dropdowns/

**Comment by adamwathan** [comment]
This is out of the scope of this project unfortunately because it's impossible to provide a dropdown without imposing aesthetic design decisions, and because Tailwind has no JS component for providing the interactivity like Bootstrap does.

Here's a simple example of how you could build your own with Tailwind and Vue.js:

https://jsfiddle.net/16sjk3br/1/

**Comment by camiant** [comment]
Just an addition for closing on outside-click
[https://codesandbox.io/s/qvow6lvp64](https://codesandbox.io/s/qvow6lvp64)

**Comment by 2567910** [comment]
could you add an option with jquery?

**Comment by vedmant** [comment]
Would be nice to have official examples in documentation of how to implement popular components. So it's easy to copy paste and modify.

**Comment by MartijnHarmenzon** [comment]
A Vanilla JS example would be nice.

**Comment by vricop** [comment]
This is what you can find in Tailwindcss webpage:

> Most CSS frameworks do too much.

 They come with all sorts of predesigned components like buttons, cards, and alerts that might help you move quickly at first, but cause more pain than they cure when it comes time to make your site stand out with a custom design.

 Tailwind is different.

 Instead of opinionated predesigned components, Tailwind provides low-level utility classes that let you build completely custom designs without ever leaving your HTML.

I think the message is pretty clear. This is more like a css library than a framework.

**Comment by harmenzon** [comment]
I fully agree with that. That's why I am trying to switch from Bulma to Tailwind. However, currently Tailwind shows a video example with Vue. I would prefer not to use any JS frameworks. Therefore, an example without Vue would be nice.

**Comment by vricop** [comment]
> I fully agree with that. That's why I am trying to switch from Bulma to Tailwind. However, currently Tailwind shows a video example with Vue. I would prefer not to use any JS frameworks. Therefore, an example without Vue would be nice.

Tailwind is framework agnostic (If I'm not wrong). You can even use it in plain HTML. If, by JS Frameworks, you mean no NPM/NODE, that's a different thing.

**Comment by vricop** [comment]
> I fully agree with that. That's why I am trying to switch from Bulma to Tailwind. However, currently Tailwind shows a video example with Vue. I would prefer not to use any JS frameworks. Therefore, an example without Vue would be nice.

**Plain html video in Adams' youtube chanel**: https://www.youtube.com/watch?v=_JhTaENzfZQ&list=PL7CcGwsqRpSMgVc5NxXUpqmGOS9s1YrWF
