### ISSUE TITLE
no package-lock.json but yarn.lock

### ISSUE THREAD

**Issue by DanielRuf** [tailwindcss/tailwindcss#338]
Is it intended to just have a yarn.lock file and no package-lock.json file?

**Comment by julienbourdeau** [comment]
It seems pretty hard to maintain the 2 in sync in the repo. Am I missing something?

**Comment by DanielRuf** [comment]
Also interesting
https://github.com/yarnpkg/yarn/issues/3614
https://github.com/imsnif/synp

**Comment by adamwathan** [comment]
The recommendation from the Yarn team is to commit lock files even for libraries:

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

I personally use Yarn and not NPM which is why there happens to not be a package-lock.json file. I'm not sure if there's a recommended workflow out there for maintaining both and keeping them up to date though.

Open to suggestions or opinions on best practices here, but going to close this as an "issue" and just leave it open for discussion.
