### ISSUE TITLE
.hidden does not work with flex

### ISSUE THREAD

**Issue by GERJohnson** [tailwindcss/tailwindcss#345]
if I have `flex` and `hidden` in one class  the  `flex` class seems to overide the `hidden` class. I feel the `hidden` class should have higher importance

Here is a fiddle link: https://jsfiddle.net/338mbbr5/1/

```html

<div class="hidden flex">
content is still visible
</div>

<div class="flex hidden">
content is still visible
</div>

<div style="display:none" class="flex">
content is hidden
</div>

```

**Comment by tlgreg** [comment]
Flexbox is a separate generator/module and both are adding a display property, that's the reason.
But agree, `.hidden` would be better defined after `.flex` and `.inline-flex` so it can easily override those classes too.

**Comment by devcircus** [comment]
Seems expected, especially the first and last scenario. Maybe some tweaks could be made to accommodate the second.

**Comment by benface** [comment]
The first and second scenarios are exactly the same. The order of classes on an element doesn’t matter (unless you use the “attribute starts/ends with” selector but that would be really weird and unreliable).

**Comment by tlgreg** [comment]
Hidden is already defined as the last display utility so it can override others by just adding it (i.e.: `<i class="inline-block hidden"></i>` will be hidden), flex display values are the exception. But yes, the first two examples in the opening post are practically identical.

**Comment by adamwathan** [comment]
I don't really think of this as a bug; both `hidden` and `flex` set the `display` property, so IMO you should expect undefined behavior here really. Something can't be hidden and flex, it can only be one or the other, so you should only add one of those classes.

To me it's like saying "I have an element with these classes `bg-purple bg-blue` but the background is purple instead of blue"; only one of them can work, why should purple work instead of blue?

I'll think on this a bit longer in this case because I understand why you'd want it to work this way, but  in general you should try to avoid adding two classes to the same element that set the same property.

**Comment by sorinr** [comment]
@adamwathan [here](https://codepen.io/sorinr/pen/OOKPzG) an example on how i used both classes hidden and flex for the same html element to change the display in the docs example: https://tailwindcss.com/docs/examples/navigation#responsive-header . Is it the right way or it can be achieved some other way?
Thanks.

**Comment by adamwathan** [comment]
Sorry I don't see exactly where you're doing it in the example, but the idea is that if you want to add `hidden`, you should also remove `flex` at the same time. They are competing for the same property (`display`) so you should avoid having both classes on the same element. It's fine to combine the responsive versions like `flex md:hidden` since they kick in at different times, but you really shouldn't have `flex hidden` on an element, you should just have `flex` or `hidden`.

**Comment by sorinr** [comment]
@adamwathan it is in here:
```
<!--  using both hidden and flex on same element  -->
  <div class="hidden w-full block flex-grow md:flex md:items-center md:w-auto" id="menu">
```

**Comment by adamwathan** [comment]
I don't see you using both there, only `md:flex`, not `flex.

**Comment by sorinr** [comment]
@adamwathan yes u r right as they trigger at different times it should be no problem

**Comment by itzikbenh** [comment]
@adamwathan You're saying that this is a competition and something can't be hidden and flex. You're correct. You just need to pick the winner. I'm pretty sure most would agree that hidden should be the winner as there's no other reason to add such a class.

**Comment by adamwathan** [comment]
Like I mentioned before, applying two classes that set the same property is a bad idea. Instead of `class="inline-flex hidden"` just use `class="hidden"`, no more problems! 😄

If it was trivial to make this work I'd have no problem doing it but it involves some somewhat annoying decisions because `flex` and `inline-flex` live in a different module than the other display helpers. I'm still open to making this work but it's not a quick fix and I don't have time right now to spend a few hours trying out different ideas and weighing the different trade-offs.

**Comment by benface** [comment]
I agree, although I can see a use case where JavaScript is used to add the `hidden` class to elements that could have any other class setting the `display` property (`block`, `flex`, etc.) and we would expect those elements to be hidden regardless of that. But it's trivial to also remove any such class and re-add it when `hidden` is removed. Also, another argument against this change:

```
<div class="flex sm:inline-flex hidden">
    ...
</div>
```

We would expect this element to be hidden all the time, but on a `sm` screen or above, `inline-flex` would actually take precedence. So I think the change would add more confusion than it would solve.

**Comment by adamwathan** [comment]
That's a great example and you're right, to "right" way to hide something would be to add `hidden sm:hidden md:hidden lg:hidden xl:hidden` to an element.

I think if you want to be able to force-hide something with a single class, I would recommend adding a new utility yourself like:

```css
.hidden\! {
  display: none !important;
}
```

...which you could add to elements like:

```html
<div class="flex sm:inline-flex hidden!">
    ...
</div>
```

**Comment by dimsav** [comment]
Maybe a cleaner approach would be to do this:

```css
.flex.hidden {
  display: none;
}
```

**Comment by Noorullah-Ahmadzai** [comment]
> I don't see you using both there, only `md:flex`, not `flex`.

This makes sense! Love it. Works for me!

**Comment by kirqe** [comment]
```
.box {
  @apply flex;

  .collapsed {
    @apply hidden;
  }
}


visible
<div class="box">content</div>

vissible
<div class="box hidden">content</div>

hidden
<div class="box collapsed">content</div>
```

This is confusing

**Comment by adamwathan** [comment]
@kirqe If your `box` class is defined at the end of your stylesheet then that is expected, because your CSS effectively looks like this:

```css
.flex { display: flex }
.hidden { display: none }
.box { display: flex }
.box.collapsed { display: none }
```

So when you apply `hidden` and `box` at the same time, `box` "wins" since it is defined last.

**Comment by younuskhan1** [comment]
I need a solution that, an element will be flex as well as hidden but conditionally I will show and hide the element.

**Comment by brunonoatto** [comment]
Com React , utilizando mobile first consegui fazer o menu ficar responsívo e com flex tanto no mobile quanto no browser. Segue código abaixo.

![image](https://github.com/tailwindlabs/tailwindcss/assets/33487330/f157a0ab-eb66-48f5-b9b1-2d4aeb2806ea)

**Comment by jspm2013** [comment]
> I need a solution that, an element will be flex as well as hidden but conditionally I will show and hide the element at tailwind css.

we all need stuff

**Comment by wsediboy** [comment]
To anyone who is struggling with this issue, I successfully done it this way:
I using conditional selector as have more elements, but you can use your element ID, it should work.
div[id^="row_config"].hidden { display: none !important; }
div[id^="row_config"]:not(.hidden) { display: flex !important; }
