### ISSUE TITLE
[Feature proposal] Background-image reset

### ISSUE THREAD

**Issue by illycz** [tailwindcss/tailwindcss#436]
For responsive variants would be useful something like `.bg-none` for `background: transparent`.

**Comment by adamwathan** [comment]
We actually do have `bg-transparent` already, do you need something different than that?

**Comment by hacknug** [comment]
I agree it would make sense to have a utility for resetting the background-image of an element (plus it would have almost no impact on the file size).

My only _issue_ with this would be that adding a new module just for this wouldn't make much sense and, since someone might need to define multiple background-images, this would be something a plugin should take care of.

**Comment by illycz** [comment]
@adamwathan `bg-transparent` does not reset background-image.

**Comment by hacknug** [comment]
It doesn't but it does the exact same thing as `background: transparent` which you mentioned.

**Comment by illycz** [comment]
I don't thing so. Tailwinds `.bg-transparent` generate `background-color: transparent` which not remove background image. `background: transparent` remove background image.

**Comment by adamwathan** [comment]
Coming back to this, can you give an example of usage? Do you have your own custom utilities for adding background images right now? If not, how are you adding background images that you want to remove with this class?

**Comment by NicolasGiuristante** [comment]
Here is an example, not an everyday problem but I wanted such a utility class myself:

I have an asymmetric layout with a background image :
`bg-contain` `bg-right` `bg-no-repeat`

On mobile, it's atrocious and would like to remove it, I could be able to use those responsively :
`user-bg-id` `bg-black` `bg-image-none`(figurative) `lg:bg-contain` `lg:bg-right` `lg:bg-no-repeat`

Where:
`user-bg-id` -> background-image { url(); }

Not sure if it makes sense nor if I'm correct with this approach, but that would just be useful. Otherwise I have to create it with media queries and such. 100% doable yet requires ugly custom CSS.

**Comment by rellect** [comment]
I think `bg-none` can be useful, but for `background-image: none` and not for the suggested `background: transparent`.

**Comment by adamwathan** [comment]
Since the only way for `bg-none` to work would be for you to implement all your custom background images as classes as well (inline styles will, or at least should, trump classes), going to close this as a "best done by the user if they need it" sort of thing.

It may be useful to explore adding a dedicated backgroundImage core plugin where you can provide URLs to your own background images but I think we can discuss that in a separate issue if people want it.

**Comment by AndrewKiri** [comment]
`bg-transparent` seems to not exist, applying `hover:` modifier also yields an error `hover:bg-transparent`
<img width="1904" alt="Screenshot 2022-02-08 at 23 13 17" src="https://user-images.githubusercontent.com/13384229/153084467-47d36d83-5aa9-4989-8986-7a63ea4829c6.png">
<img width="1874" alt="Screenshot 2022-02-08 at 23 13 44" src="https://user-images.githubusercontent.com/13384229/153084536-eec43102-2940-4ebe-addb-7dac690bce8b.png">
