### ISSUE TITLE
Setting default max-width and height for img tag 

### ISSUE THREAD

**Issue by mvdnbrk** [tailwindcss/tailwindcss#506]
Pull request #426 sets height to auto in combination with a default value of max-width to 100% to the `img` tag.

This gives unexpected results. 
See [Codepen](https://codepen.io/anon/pen/JZZjXY).

Loading a 100x200px image fills up the whole space although I am setting width and height specifically.

@adevade mentioned code from [Bootsrap](https://github.com/twbs/bootstrap/blob/7b766e1ad53b0c22de42dac04d2472f287334e2a/scss/mixins/_image.scss#L10-L16), but this is meant for a fluid image with class name `image-fluid`.

I took a look at the source code of [BeardCSS](https://github.com/monarkee/beard/blob/9bfa6232dec8e0c37c456b05db81fd88071ff1d6/stylesheets/_base.scss#L45-L56). 
BeardCSS is setting only a max-width of 100%, if width or height attributes are set they will be respected by resetting max-width to none on the `img` tag.

I think we should take the BeardCSS approach.

Example of same [code](https://codepen.io/anon/pen/pKKorY) as above with the BeardCSS approach gives the expected result.

**Comment by benface** [comment]
A couple things...

1. In your first Codepen, you used `width: 100%` instead of `max-width: 100%` like Tailwind, which doesn't "fill up the whole space". With `max-width: 100%` it behaves as expected, simply scaling the image down when its intrinsic width is larger than its container.

2. In your second Codepen, your syntax for CSS comments is incorrect (`//` instead of `/* */`), which breaks the CSS (the second rule is not applied). But even if it didn't, I don't believe that rule (the `img[width], img[height] { max-width: none; }` one) should be in the core. For one, it's more specific than a single class selector, which means Tailwind's `max-w-` classes will not be enough to re-set the `max-width` to `100%` or any other value. But also, I think the default `max-width: 100%` rule is quite useful, whether an img has width/height attributes or not. Those attributes are mostly hints to the browser anyway, they should reflect the image's intrinsic size (which is used whether the attributes are present or not, unless the width/height are set in CSS). I think it's pretty rare that we want an image to overflow its container, regardless of its intrinsic/preferred size.

That begs the question: what unexpected results did you experience?

**Comment by mvdnbrk** [comment]
Updated [Codepen](https://codepen.io/anon/pen/OEEVyM) to point out the issue.

**Comment by benface** [comment]
I don't understand the problem. If I remove this from the Codepen:

```
img { 
    max-width: 100%;
    height: auto;
}
```

...the result is the same. Also, did you intentionally use a different `width` attribute (250 pixels) than the actual image (750 pixels)?

**Comment by mvdnbrk** [comment]
Yeah that's because of the wrapping flex container.

If you remove this line:
`` height: auto;``
The image is in the expected width and height as set by the width and height attributes.

**Comment by benface** [comment]
Ah, my bad. The result is not the same; my browser was too small for me to notice the difference. OK, I see what's going on. I would say that this is an edge case as it's only a problem with images in flex containers. In fact you can solve it by wrapping the `img` in an extra `div`, or by adding `align-items: flex-start` to `.flex` (`items-start` in Tailwind). By the way, your solution of...

```
img[width], img[height] {
  max-width: none;
}
```

...doesn't work because in this specific case, the problem is not even `max-width: 100%`, it's that you are scaling the image down yourself with smaller width/height attributes, and `height: auto` overrides the height attribute. But more importantly, this problem would occur even if the `img` didn't have width/height attributes (try removing them and resizing your browser, you'll see).

**Comment by mvdnbrk** [comment]
Okay thanks.

Well putting the image in an extra div or adding ``.items-start`` to ``.flex`` just feels like a workaround for me.

I really needed some time to figure out where this unexpected behavior did come from.

**Comment by benface** [comment]
> Well putting the image in an extra div or adding .items-start to .flex just feels like a workaround for me.

It is and it isn’t. I agree that it’s unfortunate that Flexbox behaves this way with images, but I’m pretty sure it’s per the spec (i.e. not a browser bug). The default value of `align-items` is `stretch`, and I guess if there’s only one item it looks at its intrinsic height and uses that.

> Tailwind already provides a .h-auto utility, so maybe if you need to set that property it would be better to use .h-auto instead of adding it by default to the img tag?

Just in case it wasn’t clear, this is not even caused by `height: auto`. It’s just making the problem more apparent because you immediately end up with an image with an intrinsic height (3000px) that doesn’t match the aspect ratio inferred by its display width (250px). You would have the same problem without `height: auto` if the flex container was smaller than 250px. I guess an easier way to show that is to use the actual image size (750 x 3000) as the display size (either by removing the width/height attributes or by setting them to 750 and 3000 respectively) and resizing the window. You’ll see that below 750px, the image starts getting stretched with no regard to its aspect ratio again.

**Comment by adamwathan** [comment]
Here's a Codepen showing the same issue without `height: auto` set for reference:

https://codepen.io/adamwathan/pen/dKKMJb

I'll admit I'm tempted to remove these styles completely and just let people use `max-w-full` and `h-auto` as needed, but it is pretty convenient :/ In this case I think seeing the image stretch in height is not completely *unexpected* at least, because flex items do stretch to fill the container unless you specify otherwise with `align-items`.

**Comment by benface** [comment]
Removing these styles completely would also be a good option. My point was that as long as Preflight has `img { max-width: 100%; }`, `height: auto` should be included as well (for the reasons in #426) since the issue described here is caused by something else. But yeah, it would make sense to let the user deal with that. There are (rare) cases in which you may want an image to overflow... and if not, you can easily add these rules in a custom reset on top of Preflight. I am planning on releasing a "opinionated reset" plugin for Tailwind, and I'll definitely include them if you remove them.

**Comment by benface** [comment]
In fact, I already add this to my own projects:

```
img, svg, video, iframe {
    display: block;
}

img, svg, video {
    max-width: 100%;
    height: auto;
}
```

The `display: block` fixes vertical alignment issues (replaced elements are `inline` by default so they are affected by surrounding text, line height, etc.), and I set `max-width: 100%` and `height: auto` to `svg` and `video` as well for consistency.

**Comment by mvdnbrk** [comment]
I agree with @adamwathan  setting ``max-width: 100%;`` is pretty convenient.

In the [Codepen](https://codepen.io/adamwathan/pen/dKKMJb) by Adam the image gets another aspect ratio due to the fact it is placed in a parent div with a width of 100px. But the image stays at a height of 1000px as I would expect.

If you bring back the ``height: auto;`` property the image will stetch to a 3000px height.

**Comment by hacknug** [comment]
What about adding `align-self` to the img element on preflight? This would only do something in case the image it's inside a flex container.

**Comment by grund3g** [comment]
Even if the `height: auto` is not the main problem here, i would remove it by default because there is no way to unset `height: auto` with css afterwards.

**Comment by ulfw** [comment]
Since this issue is still open maybe my case has something to do with it.
I try to make an image have 100% of the height of the parent, keeping aspect ratio.
But the image is not displayed in the desired div, only if I use only the image tag and class max-h-full.
But as a link inside a div it does not work:
https://codepen.io/anon/pen/omLBaj?editors=1000
What is wrong here?

**Comment by benface** [comment]
@grund3g I agree with you. And since `max-width: 100%` without `height: auto` introduces the issue described in #426, I would remove this rule altogether:

```
img {
    max-width: 100%;
    height: auto;
}
```

In fact I ended up undoing that rule (as much as possible, because like you said you can't fully undo `height: auto`) in my opinionated reset that I use on top of Preflight in every project: https://github.com/benface/tailwindcss-config/issues/6

That being said, Preflight is completely optional and Adam has said on Twitter that he was working on a way to let plugins define custom "base styles". So you could make your own reset plugin that doesn't include the above rule, should Adam decide not to remove it from Preflight.

**Comment by adamwathan** [comment]
Just for reference, here's a truly simplified demo that illustrates the core problem, which is that if you specify an explicit height using the `height` attribute, `height: auto` defeats it and there's no way we can force the browser to respect the explicitly defined height attribute:

https://codepen.io/anon/pen/GeOoJe

You can see there I am trying to force the image to stretch but I can't make it happen. Now that I'm typing this though I'm realizing the **obvious** solution is to use inline styles instead of the width and height attributes:

https://codepen.io/anon/pen/GeOoJe

🤦‍♂️ 

So I think I might revert this change since it's actually trivial to work around...

**Comment by himynameisphil** [comment]
This feels counter intuitive to me. Max width 100% and Height auto both exist as a class, why wouldn't you just add them as you see fit? Or declare them globally if really you want to. Forcing them means it's difficult to override, especially for content generated by authors through a CMS for example.

We've gone from..

`<img src="image.png" width="170" height="30">`

to

`<div class="flex" style="width: 170px; height: 30px;"><img src="image.png"></div>`

Please consider removing it again.

**Comment by himynameisphil** [comment]
Came across another reason to consider removing these default styles.

max-width being the culprit this time: [https://codepen.io/himynameisphil/pen/poojXwr](https://codepen.io/himynameisphil/pen/poojXwr)

**Comment by silvio-e** [comment]
That just drove me nuts. It was unexpected. That I can't use the height attribute is for me too much of an opinion as it disables a default HTML behavior. And I didn't find it documented anywhere. Seems like I can't disable it, right? So you first have to figure out what happens, which wastes time and then use inline styling to overwrite it? That is kind of counter intuitive and not very elegant. :/

**Comment by tordans** [comment]
Looking at https://github.com/tailwindlabs/tailwindcss/commit/ee27bbac9912b843e2c9ee3d3e9c7b9acd80a1d3 i thought that 2.0.3 already has this since its tagged with v2.0.3. 

But looking at https://github.com/tailwindlabs/tailwindcss/compare/v2.0.2...v2.0.3 I don't see the change. Which would also explain why its not part the changelog, yet.

Does anyone know if this commit is in fact not released, yet?

**Comment by samtstern** [comment]
Just spent the better part of a day figuring out why my `<img` tags were not working! Eventually realized it was `height: auto` overriding things like `height="123px"`.

So is there any way to stop Tailwind from adding `height: auto` to `img`?

**Comment by adevade** [comment]
This issue pops up from time to time. I'm personally fine with how it works today, but I see that some people above are having issues. Mostly with content from CMS's it seems.

Could this, or some variation of it, maybe be a solution? I'm talking for the prefligh styles in the framework.
Only setting `height: auto` on `img` if the element does not have a height attribute defined.
```css
img:not([height]) {
  height: auto;
}
```
https://codepen.io/adevade/pen/PopQrYZ?editors=1100

Sorry to bother you @adamwathan, but maybe you could take a quick look at this or make a new comment, since it was a couple of years ago now. Thank you.

**Comment by samtstern** [comment]
@adevade you're right, my use case is CMS-like as well. I have user-generated markdown content which I parse and then style with [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) so in order to reach in and add explicit height styles I have to parse the HTML with JavaScript, which is a shame because I love how hands-off it can be otherwise.

**Comment by adamwathan** [comment]
Hey @adevade! That would be a great solution but it has a higher specificity than a class:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/4323180/120625091-57c57f00-c42f-11eb-9f68-6b544b91ff6f.png">

That means that classes like `h-32` would just stop working, because this base style would override the height back to auto.

@samtstern For this problem I've typically just recommended people use inline styles instead of the height attribute, which will always work and override the `height: auto` we set in our base styles. Maybe it's something we can change for 3.0 but a bit hesitant because it's a pretty huge breaking change for people.

**Comment by samtstern** [comment]
Is there a simple way to make this configurable?

**Comment by adamwathan** [comment]
I think you could add this to your own CSS (haven't tested):

```css
img {
  height: unset
}
```

**Comment by dkodeit** [comment]
> img {
  height: unset
}

This doesn't work per spec.

**Comment by natebrunette** [comment]
This behavior was extremely unexpected. I think it would be best to not add styles you can't easily undo.

**Comment by simonmaass** [comment]
I also ran into this issue today when using the nuxt/image module in combination with tailwindcss

**Comment by doxigo** [comment]
Having the same issue that the `img` tag height doesn't apply in a react app, any solution to get rid of the `height: auto` and  `max-width: 100%;` from `img` and `video` tag only?

**Comment by wtchnm** [comment]
Here's a PNPM patch to remove these styles:

```diff
# patches/tailwindcss@3.3.5.patch

diff --git a/lib/css/preflight.css b/lib/css/preflight.css
index e5e52cd8f32310089aebc65cfd943248cfe7b92e..c32f29ba3b8e189b0b3471c3d0d69da64fec0a50 100644
--- a/lib/css/preflight.css
+++ b/lib/css/preflight.css
@@ -362,16 +362,6 @@ object {
   vertical-align: middle; /* 2 */
 }
 
-/*
-Constrain images and videos to the parent width and preserve their intrinsic aspect ratio. (https://github.com/mozdevs/cssremedy/issues/14)
-*/
-
-img,
-video {
-  max-width: 100%;
-  height: auto;
-}
-
 /* Make elements with the HTML hidden attribute stay hidden by default */
 [hidden] {
   display: none;
```

**Comment by BorysShulyak** [comment]
> Having the same issue that the img tag height attribute doesn't apply in a react app, any solution to get rid of the height: auto and max-width: 100%; from img and video tag only?

The same issue, could not use a Next.js Image component

**Comment by quangle36** [comment]
Still facing the same issue, is there any update?

**Comment by AayushKarki714** [comment]
> > Having the same issue that the img tag height attribute doesn't apply in a react app, any solution to get rid of the height: auto and max-width: 100%; from img and video tag only?
> 
> The same issue, could not use a Next.js Image component

Any updates on how to use with Next js Image??

**Comment by Josevictor2** [comment]
up

**Comment by nezi311** [comment]
Any updates on this?

**Comment by sunananus** [comment]
The issue persists: when using the Image component in Next.js, the width and height styles are being overridden.
img { 
    max-width: 100%;
    height: auto;
}

**Comment by philipp-serfling** [comment]
Would someone please remove this!
I find this rule very counter intuitive and misleading, just spent 1hour to figure this out.
Very inconvenient :/
