### ISSUE TITLE
Invalid CSS after "...wind preflight;": expected 1 selector or at-rule, was "{}"

### ISSUE THREAD

**Issue by musman92** [tailwindcss/tailwindcss#534]
my tailwind css version is 0.6.5 and i am using laravel-mix with SAAS
i add 
`@tailwind preflight;
`
in sass file. and got this error

Module build failed:
@tailwind preflight;
                   ^
      Invalid CSS after "...wind preflight;": expected 1 selector or at-rule, was "{}"
      in F:\...\resources\assets\sass\index.sass (line 8, column 21)

 @ ./resources/assets/sass/index.sass 4:14-268
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/index.sass

**Comment by adamwathan** [comment]
This is due to Sass being picky about custom at-rules, I believe you can solve it by writing this instead:

```
@tailwind preflight {}
```

Or alternatively use Sass' import feature to import our unprocessed CSS files:

```
@import "~tailwindcss/preflight";
@import "~tailwindcss/components";
@import "~tailwindcss/utilities";
```

Sass should inline those CSS files but not process them, so the `@tailwind` calls inside of them will be ignored by Sass but processed by Tailwind.

**Comment by musman92** [comment]
@adamwathan  thank you buddy.
