### ISSUE TITLE
Outline utilities

### ISSUE THREAD

**Issue by m1guelpf** [tailwindcss/tailwindcss#56]
How about adding a helper to add/remove outline?
I am currently facing a situation where I want to remove the focus outline of an input field and, AFAIK, there aren't utilities for this on Tailwind...

**Comment by luizbills** [comment]
`outline: 0` is not recommended, it's anti-accessibility pattern.

**Comment by reinink** [comment]
@luizbills That's only if you don't implement your own custom outline, correct?

**Comment by davidhemphill** [comment]
@m1guelpf I want this as well. I think we'd want to add some good `:focus` utilities alongside it, so people don't just remove the outline and not provide an alternative. 

@luizbills It's generally recommended to leave the outline, but if you change the look of the element on focus, it's fine.

**Comment by PILO7980** [comment]
I've build my own utility classes framework, but not as good and configurable as Tailwind, and I used somthing like `:bg-primary` for both `:focus` and `:hover`

![hoverandfocus](https://user-images.githubusercontent.com/3218536/32407389-540d197a-c188-11e7-84d1-03734d6f8484.jpg)

It's shorter and does the job.

**Comment by wilburpowery** [comment]
+1 for this. Would still be very helpful.

**Comment by reinink** [comment]
I started hacking on new outline module today, but I'm seriously wondering if we need anything here beyond a reset (`outline-none`). The main issue I have with outlines is that they don't follow border radiuses, meaning you get this:

```css
outline: 2px solid rgba(52,144,220,0.5);
```

![image](https://user-images.githubusercontent.com/882133/41426119-b257c81c-6fd0-11e8-8886-029244047921.png)

What I typically use in these situations is a box shadow, which DOES following the border radiuses:

```css
box-shadow: 0 0 0 2px rgba(52,144,220,0.5);
```

![image](https://user-images.githubusercontent.com/882133/41426354-5740ab0a-6fd1-11e8-821a-aa5f149d843c.png)

And since we already have the box shadow module setup, adding an "outline" like this is trivial:

![image](https://user-images.githubusercontent.com/882133/41426428-9561acf4-6fd1-11e8-9923-ff54a62fe47a.png)

**Comment by benface** [comment]
@reinink Outlines follow border radiuses in Safari. Too bad other browsers don't follow suit!

There's a Chromium bug open here:
https://bugs.chromium.org/p/chromium/issues/detail?id=81556

And a Mozilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=315209

**Comment by reinink** [comment]
@benface Oh nice, thanks for sharing. So this _might_ get fixed some day, but in the meantime, maybe we're better pushing folks to use box-shadow instead.

**Comment by benface** [comment]
Definitely. Box-shadow is great for external borders.

**Comment by m1guelpf** [comment]
@reinink What about the reset?

**Comment by sumitwagh** [comment]
How to change input field outline color??
