### ISSUE TITLE
[BUG] svg:not(:root) unexpected behavior in chrome

### ISSUE THREAD

**Issue by frankspin89** [tailwindcss/tailwindcss#570]
The following ie11 fix has unexpected behavior in chrome 69

```
/**
 * Hide the overflow in IE.
 */

svg:not(:root) {
  overflow: hidden;
}
```
With tailwind preflight the inline svg image has different stroke widths., and is causing some unexpected behavior. 

I made a simple codepen to illustrate the problem.  (the outer lines are changing in  line width. 

**Without Tailwind preflight**
https://codepen.io/frankspin/pen/rqxqXr

**With Tailwind preflight**
https://codepen.io/frankspin/pen/xyZyvM

**Comment by adamwathan** [comment]
This style actually comes from Normalize and Normalize has removed it for version 8.0, which we are using on master and will be using in v0.7.0 👍 

So going to close this as fixed as that style will be removed in the next release.

What's really happening there btw is just that the SVG's container has overflow set to hidden, so the stroke is being cropped because it leaks outside the container.

Here's an example with that style that's easier to see:
https://codepen.io/adamwathan/pen/EdPOQB?editors=1100

And with that style removed:
https://codepen.io/adamwathan/pen/LgGXeE?editors=1100

**Comment by adamwathan** [comment]
You can work around this in the mean time by just adding `overflow-auto` to your SVG element.
