### ISSUE TITLE
Documentation mentions 'smoke', but it doesn't exist in the default config

### ISSUE THREAD

**Issue by bhulsman** [tailwindcss/tailwindcss#59]
The documentation mentions the color 'smoke', which I presume is a translucent black/grey color. Most notable `.bg-smoke`, but I've found some more sprinkled around.

Since it's not an actual value in the default config, I was wondering if it's missing or removed on purpose.

**Comment by adamwathan** [comment]
We changed our grey scale about a week before release but the docs were still loaded with the old references and haven't had a chance to update everything yet. Would love PRs for changing those things, even if its just tiny ones here and there changing one reference and making the docs .01% better than they are 😄

**Comment by bhulsman** [comment]
OK, so it's just a shade grey? I was expecting it to be something like `rgba(0, 0, 0, 0.2)` for backgrounds. But I'll guess I'll add translucent background to the config myself.

I'll might have some spare time tomorrow for creating some PRs. Besides; tags like 'help wanted' or 'PRs welcome' would make it easier to find actual to do stuff in the issues.

Thanks for the quick response. Currently trying tailwindcss on a new project. Very pleased so far btw, good job! ^^

**Comment by adamwathan** [comment]
Yeah, originally we were struggling to get by with only 7 shades of grey, so we decided to split the greys in half. Dark greys were "slate", and light greys were "smoke", and each of those had their own shades.

Then we decided to make `black` actually be our darkest grey, giving us 8 shades of grey to work with using our darkest/darker/dark/base/light/lighter/lightest naming scheme, and that ended up being just enough to collapse everything back to just grey-{shade} instead of the two separate scales 👍
