### ISSUE TITLE
Placeholder color for input and textarea is off the default color palette

### ISSUE THREAD

**Issue by andgordio** [tailwindcss/tailwindcss#615]
Tailwind's default color palette is great for creating quick and consistent designs. Having some of the colors assigned by default (eg border-color) also contributes to consistency a lot.

Currently placeholder in inputs and textareas has the default half-transparent black color which makes forms look a little off.  Since inputs are present in almost every project (my guess), maybe matching placeholder's color to the Tailwind's palette by default could be a good idea?

<img width="373" alt="greys" src="https://user-images.githubusercontent.com/31099945/51088826-5ff0c700-176d-11e9-9f06-9316e16fc8ef.png">

**Comment by adamwathan** [comment]
By default we actually set the placeholder to the same color as the text for the input, but with the opacity dropped to 50%. We did this because it seemed like a sane way to match the actual text color simply, for example if you have an error state on a form field and you make the text red, the placeholder will become a semi-transparent red:

![image](https://user-images.githubusercontent.com/4323180/52384344-30bb3600-2a4b-11e9-92a5-24d995dc6aa9.png)

Agree in a perfect world it would just be a proper color from the palette instead of using the opacity hack, but I think until we natively add support for styling placeholders with utilities (like `placeholder-grey-light` or something), what we have now is probably the best solution 😕

The tricky thing with providing native support for placeholder styles is it's hard to decide whether it should be a utility (like `placeholder-red`) or a variant (like `placeholder:text-red`). A variant probably makes the most sense and would be easy to add, so maybe we can get something like that in for the next release.

**Comment by andgordio** [comment]
Thanks for the detailed explanation! I was also delighted to learn from your latest journal post that people who rely on default styles are not a niche group of Tailwind users.

Having placeholder's opacity set to .5 makes sense, and having access to changing its style through a utility or a variant could be a great addition to the framework. Meanwhile, I have another suggestion on how to fit placeholder's look into palette, and I'm sorry if it gets too picky 😶

Do you think it makes sense to set the default style for placeholder to Tailwind's black instead of pure black (and keeping the opacity set to .5)? The change is not of the most pronounced ones, but it does remove false-red saturation that pure-black placeholder receives from all the blue-saturated greys around it:

<img width="446" alt="black-v-tailwind" src="https://user-images.githubusercontent.com/31099945/52407571-63137480-2ad9-11e9-86f0-1389210a7613.png">

I realize this may lead to inconsistencies because the default text color is pure black, and that is done for a reason. But I still believe this minor fix could improve the default look of forms created with Tailwind without breaking Tailwind's design system. For example, iOS — a design system that I believe took saturated greys mainstream — uses purple greys almost everywhere, including placeholders, and pure black for text:

<img width="402" alt="black-vs-ios" src="https://user-images.githubusercontent.com/31099945/52408205-0749eb00-2adb-11e9-8d61-63da8de85594.png">

Anyway, thanks for your great work!

**Comment by adamwathan** [comment]
> Do you think it makes sense to set the default style for placeholder to Tailwind's black instead of pure black (and keeping the opacity set to .5)?

Because the placeholder color is inherited from the current color you can already do this by setting `text-black` on your input/textarea:

```
<input class="text-black">
```

Personally I add `text-black` (and a few other defaults) to the `body` tag so that it's used as the default for the entire site:

```
<body class="text-black leading-tight font-sans">
  <!-- ... -->
</body>
```

The problem with hardcoding a default for placeholders is that the placeholder color wouldn't update as the text color changes. Currently the placeholder is always based on the text color:

![image](https://user-images.githubusercontent.com/4323180/52412718-9213f100-2aad-11e9-8887-71f3e8376739.png)

If we hardcoded a default placeholder color, the placeholder would be grey even in the red input:

![image](https://user-images.githubusercontent.com/4323180/52412758-b66fcd80-2aad-11e9-8154-c4a02d640d37.png)

So I think until we make it possible to customize the placeholder color with utilities, the current default is the most useful.

**Comment by andgordio** [comment]
> Personally I add `text-black` (and a few other defaults) to the `body` tag so that it's used as the default for the entire site

This actually does the job of styling forms within the color palette, thanks!

Looking forward to a placeholder utility/variant in future releases 🤞
