### ISSUE TITLE
[Feature proposal] push/pull (offset) classes

### ISSUE THREAD

**Issue by jmp909** [tailwindcss/tailwindcss#632]
Hi

in inuit css they have push / pull classes eg

`.u-pull-1/6@tablet`
`.u-push-1/4@desktop`
`.u-push-reset@wide` etc

this allows you to offset grid columns responsively

it would be great if tailwind could do this so i guess something like
`md:pull-1/6 lg:push-1/4`

`pull/push` work slightly better than `offset` since you need to be able to go in both directions

thanks
J

**Comment by adamwathan** [comment]
There's no real way to implement fairly intelligent push/pull logic using just utility classes and we try to stay away from providing anything at a high level of abstraction so it's unlikely we'll ever add anything like this to the framework unfortunately.

The only way to do push/pull columns this way as far as I know is with a float-based grid (I could be wrong), and using any flexbox-based approach you can only really do regular offsets.

A better approach to reordering things using a flexbox grid is to create your own helpers for the `order` property.

Once CSS Grid has better browser support, that will be the best option because you can position columns anywhere you want, see the "Explicit start and end points" example here: https://tailwindcss.github.io/plugin-examples/#css-grid

**Comment by jmp909** [comment]
just leaving the info for anyone looking. this is essentially doable with the `margin/negativeMargin` in the config file

`negativeMargin: { ... '1/6': '16.6666666667%' }`

then

`class="lg:-ml-1/6"` (instead of a custom pull class for eg `lg:pull-1/6`)

**Comment by mrcsmcln** [comment]
Since offsets are a very common use case, why don't we add the same column-related `width` classes to `margin`? Only reason I see against doing this is that it doesn't make a ton of sense for `margin-top` and `margin-bottom`. I've been using empty `<div>`s, which works when combined with a `flex` wrapper, but it definitely feels wasteful.
