### ISSUE TITLE
[Feature Proposal] Responsive <link media="..."> file generation

### ISSUE THREAD

**Issue by imliam** [tailwindcss/tailwindcss#653]
The `<link>` tag you use to link CSS files in an HTML document can accept a media query as an attribute - the browser will then only download files it needs based on the media queries, a significant way to reduce bandwidth for mobile users:

```html
<!-- Only load relevant stylesheets when the current screen size requires them -->
<link href="xs.css" rel="stylesheet">
<link href="sm.css" rel="stylesheet" media="@media (min-width: 576px)">
<link href="md.css" rel="stylesheet" media="@media (min-width: 768px)">
<link href="lg.css" rel="stylesheet" media="@media (min-width: 992px)">
<link href="xl.css" rel="stylesheet" media="@media (min-width: 1200px)">
```

Since Tailwind has such a huge focus on mobile-first responsive utility classes, I'd love to see a first party way to help generate these files built into the framework's tooling.

I'm not sure how this would look since the files generated ultimately depend on the configuration of other tools like Webpack, but it should be possible to make it easier through new directives or something.

My first thought would be to offer a few new directives to inject into the CSS file which would offer a limited number of the responsive utilities:

```css
@tailwind utilities; /* Remains unchanged, includes all utilities and every responsive variation */
@tailwind xs_utilities; /* Includes any utilities that aren't a responsive variation */
@tailwind sm_utilities; /* Includes any utilities that start with sm: */
@tailwind md_utilities; /* Includes any utilities that start with md: */
/* And so on... */
```

**Comment by hacknug** [comment]
I think this would be a better fit for [tailwindcss/discuss](https://github.com/tailwindcss/discuss), but here's my two cents anyway.

I'm not sure we need a new directive in Tailwind to take care of this, and in case it was going to get added it should be something that worked pretty much like `@screen` does where you can specify one of the screen values in the config file.

The issue with this approach imho is that we'd be adding things to Tailwind that I feel might not belong there (not too sure about it though). There's already a PostCSS plugin that does exactly this but I still haven't had a chance to try it out: https://github.com/SassNinja/postcss-extract-media-query

Maybe instead of this being yet another feature to be tested and maintained in core, it could simply be a wrapper that passes the right config to that plugin. This would probably just set the [`queries`](https://github.com/SassNinja/postcss-extract-media-query#queries) option given Tailwind's `screen` media queries and names.

Will try to explore this and report back. Then maybe we add documentation explaining how to accomplish it and why once we've discussed it a little more.

Just in case someone wants to read more about it, @csswizardry wrote about it in his blog a couple months ago: https://csswizardry.com/2018/11/css-and-network-performance/

**Comment by adamwathan** [comment]
Another discussion here: https://github.com/tailwindcss/discuss/issues/210

Personally I think this is a bit out of scope at least for now, and would be better handled by another PostCSS plugin (like @hacknug shared), so going to close with no plans to implement for now. Thanks though!
