### ISSUE TITLE
Feature request: add camelCase option to config

### ISSUE THREAD

**Issue by jan-at-futr** [tailwindcss/tailwindcss#682]
Hiya! I've long been into Atomic CSS, and am looking to switch from Tachyons to this, in conjunction with CSS Modules.

The issue is, CSS Modules require camelCase naming. This makes consuming Tailwind-generated CSS tricky for a few minor reason

- positive and negative values like `mr-4` and `-mr-4` will both translate to `mr4`. It's possible to disable this module, but something like `options: { negativeToken: 'minus' }` could solve this, in the same vein as `options: { separator: '...' }`.

- Actually, there's also `.w-1/2`...

Thoughts?

**Comment by adamwathan** [comment]
Can you explain the problem in more detail with an example, and maybe some info about what tools you are using? The way I understand it, CSS Modules is really just a spec and there are multiple implementations. I also can't find anything about it forcing camelcase, only recommending it so that you can access styles like `styles.fooBar` instead of `styles['foo-bar']`.

We only use the negative token for that one class so I don't really want to create a whole config option for it, instead I would recommend you just disabled the `negativeMargin` module entirely and add negative values to the regular `margin` module, maybe stuff like `mr-n4`. You can also change `w-1/2` to whatever you want since `1/2` is just a value in your config file.

In general trying to make Tailwind work entirely as camelcase would be a huge change that I don't really intend to invest any time into, because we use non-alphabetic characters all over the place.

Got an example repo maybe that shows how you have things set up?

**Comment by adamwathan** [comment]
Closing with no plans to implement but happy to continue the discussion and revisit later if necessary.
