### ISSUE TITLE
[Feature proposal] add unset classes such as `text-direction-unset`

### ISSUE THREAD

**Issue by elisechant** [tailwindcss/tailwindcss#802]
I have a use case where I want to apply `text-center` to an element and then at a breakpoint unset it, such as:

```
<div class="text-center md:text-align-unset">
```

`text-align-unset` (or a better name) would reset the element styling to inherit or normal properties, such as: 

```
.text-center { text-align: center; }
.text-align-unset { text-align: unset; }
````

To write this out in full:

```
.text-align-unset { text-align: unset; }

@media (min-width: 576px) { /* sm */
  .sm\:text-align-unset { text-align: unset; }
}

@media (min-width: 768px) { /* md */
  .md\:text-align-unset { text-align: unset; }
}

@media (min-width: 992px) { /* lg */
  .lg\:text-align-unset { text-align: unset; }
}

@media (min-width: 1200px) { /* xl */
  .xl\:text-align-unset { text-align: unset; }
}

```

**Comment by benface** [comment]
I like this idea. It would mostly be useful for inherited properties like font family, font weight, font size, text alignment, text color, etc. In fact, I don't think it makes sense for non-inherited properties.

I like the `unset` name but I think the actual implementation should use `inherit`, since `unset` is [not supported in IE11](https://caniuse.com/#feat=css-unset-value) and it does the exact same thing when used on a property that is inherited. `unset` is only useful when you're applying it to multiple properties at the same time, e.g. `all: unset`.

The only really annoying thing is the class names inconsistency, since the same `font-` prefix is used for both `font-family` and `font-weight`, and the same `text-` prefix is used for `font-size`, `text-align`, `color`, and more. So like you suggested, the unset utilities would have to be longer to avoid any ambiguity, e.g. `font-family-unset`, `font-weight-unset`, `text-size-unset`, `text-align-unset`, `text-color-unset`, etc. Unfortunately, I'm not sure that will be considered elegant enough to be part of the core, especially since you can already achieve the same effect by being more explicit / less DRY, e.g.:

```
<div class="text-left">
    <div class="text-center md:text-align-unset">
</div>
```

can be:

```
<div class="text-left">
    <div class="text-center md:text-left">
</div>
```

Still a good idea IMO, I might just add it to my https://github.com/benface/tailwindcss-typography plugin.

**Comment by elisechant** [comment]
Great thanks! yes, I agree and I see what you mean about the name inconsistency making this a little bit tricky. 

I think it's definitely a valid use case until we have an inclusive only break point syntax like `md:max-lg:h1` but I this would bloat the library significantly. 

A snippets "repository" for some of these things tho would be great too.

**Comment by adamwathan** [comment]
Going to say no to this for now but not closed to revisiting it down the road. In the mean time you could put something like this together for your own use using a plugin 👍

**Comment by ZaidBarghouthi** [comment]
@adamwathan

This is quite useful and makes the code way cleaner for multi-direction pages. Where the page can be viewed left-to-right or right-to-left (Arabic, Hebrew, Farsi, etc.).

Say I have a title that is centered on mobile.. and aligned left/right on md depending on the page dir. So `md:text-left` won't work when the page it viewed RTL.

Its not the most difficult thing to work around but it makes sense to have a reset for text alignment.

**Comment by chasegiunta** [comment]
@adamwathan Curious if you're interested in looking into this again with JIT. Would be helpful when migrating sites away from other frameworks to Tailwind. Able to do `[unset]` or `[inherit]` in some cases (like `w-[unset]`) but instances like text align classes, or other classes that share the same prefixes, can't benefit from that same escape hatch.
