### ISSUE TITLE
[Feature Request] Parsing code for minimal CSS generation

### ISSUE THREAD

**Issue by matsp** [tailwindcss/tailwindcss#887]
Hi!

Actually tailwind is doing a great job generating CSS from config values and users have to purge the unused classes afterwards. Iam asking myself if it's a good idea to just generate the needed CSS classes and not all, but their might be a bigger picture behind the core concepts. This would only apply to projects that are build by a process and not just importing the whole CSS file of tailwind. If it's a good idea (Iam not sure yet) it will make all build configs (bundler) easier because we can skip something like e.g. "purgecss" and have minimal builds directly from tailwind.

Whats your opinion?

**Comment by chasegiunta** [comment]
@matsp Check out https://twitter.com/adamwathan/status/1092553439471697921 & thread discussions

**Comment by benface** [comment]
I've also been thinking about this for a while. With the way I use Tailwind, this would be great, but I'm not sure everyone (including Adam) would agree. By that I mean that I already include as many values as possible in my config, which I turned into a module that I use in all my Tailwind projects.

For instance, my spacing scale includes all px values between 1 and 1000+ and a lot more % values than the defaults. I've tried the default 4px scale on some projects as I liked the idea at first (plus it's easier to stick with the defaults), but there were many times when I needed an in-between value (like 2px or 6px), either because it looked better or because I had to follow a design I was given. I liked the idea of consistency that a grid provides, but in reality, to my eyes at least, using a limited set of spacing options doesn't actually look more harmonious or better, it just limits my options. If you think about it, many things come into play in CSS other than width/height, padding, and margin declarations, which result in elements not all being aligned to a 4px grid anyway. Things like inline elements being vertically aligned differently depending on the `line-height` and `vertical-align` values, the line height itself depending on the `font-size` value (e.g. 14px x 1.5 = 21px, not divisible by 4), flex children being centered/justified with space between/around which, depending on the container's width, can fall pretty much anywhere on the grid, etc. So why not include all the options I may need then? I started by adding custom `1px`, `2px`, etc. values on top of the 4px scale whenever I needed them, but it felt wrong and confusing to mix them together (e.g. `p-2 pb-2px`), so now I don't use a scale at all, and `p-2` means `padding: 2px` (actually in `rem` like Tailwind does, but it computes to `2px`).

To be clear, I totally understand why this is not Tailwind's default. The CDN version is super useful for prototyping, and for it, the file size needs to be limited. But when working with a full build process, I'm able to get really small CSS even though I'm not limiting the spacing values I use, thanks to Purgecss. However, the workflow is not great:

1. It takes a long time to compile, both in dev (30-60 seconds) and even more so in production due to Purgecss (2-3 minutes). In dev, I don't have to compile as frequently as I would with another technique since the whole point is to have all the values I could possibly need already available, but it's definitely a pain point, especially when tweaking components (I guess I could separate the components into another CSS file, but then I wouldn't be able to use `@apply`).

2. As you might expect, the resulting development CSS is HUGE (10+ MB), which causes some issues in browsers. For instance, the dev tools are noticeably slower; it takes like 10 seconds to enable/disable a declaration or a class and for it to be applied. Edge even gives up after a couple hundred thousand lines of CSS, and doesn't apply the rest (or at least it didn't when I worked on a project on Windows a year or so ago).

3. I still need to add values to my config sometimes, which is annoying when it happens because of point 1, and because it defeats the purpose of the whole workflow. I would love to just keep writing HTML and for my classes to be instantly recognized as valid Tailwind classes and generated in the CSS, even if I didn't include that specific value or variant in my config. I'm not saying that every value should be valid; there should still be some constraints as to what a valid class is. For instance, something like `w-1/20` would be valid, but `width-1/20` and `w-5%` wouldn't. In that system, I suppose the config file would be a way of defining those constraints (as regular expressions? I haven't thought about that part too much), instead of defining the exhaustive list of utilities that get generated.

I'm not suggesting that scales are useless, or that limiting your options is always a bad thing. For "design tokens" such as colors, fonts, font sizes, leading and tracking, etc. it makes perfect sense to have a limited set of options, and I wouldn't have it any other way. I would also like to clarify that the general idea also works if you want to use a spacing scale such as the default 4px one, it would just be a constraint defined in the config. I was giving this as an example of a workflow that is at odds with the current way of working of Tailwind, but you could easily imagine the same problem or worse with "free-form" CSS properties such as `transform`, `transition`, `clip-path`, CSS grid, gradients, etc.

Finally (this is getting quite long), I would like to add that I have no idea if this is technically possible. I guess it involves writing a parser of some sort, which may not be performant at all, and maybe the ideal workflow I have in mind would actually be shit because compiling the CSS each time the HTML is saved is too slow. Still, I feel like there is definitely something to that idea, and I would love to hear other people's thoughts.

**Comment by benface** [comment]
Forgot to say one thing (haha)... one downside of that approach would be that it would make it impossible to use Tailwind to design in the browser with dev tools like some people do, because the CSS would only include what's already in the HTML when the page is loaded. I don't do that, but I admit it's a pretty cool workflow. Now of course, it wouldn't be impossible to write a dev tools plugin that generates CSS on the fly as you add classes to the HTML, but it's getting pretty complicated.

**Comment by danielstaleiny** [comment]
I prefer idea of having most styles on and in production purge the css to remove un-used styles. It feels much better to have it like that instead of going back and forth in config file. The parts I am sure I am not going to use are toggle off, from everything else I will generate cheatsheet and follow that. Stress free development.

**Comment by tlgreg** [comment]
What Adam mentioned in his tweet is auto-detecting special characters in the config, which sounds good, but honestly, I would prefer some kind of a function which merges your config then returns the special characters it found, alternatively an extractor function too for majority purgecss cases.
This would be more flexible for different types of workflows.

Tailwind docs default extractor can - for example - fail in some contexts, an example being when class-names are used as object properties the trailing colon breaks matching single-word utilities. This could be fixed in a tailwind extractor but I feel like it is another level of maintenance, that should be left for the specific libraries and to build setups in userland.

**Comment by janielMartell** [comment]
What if we just make it a flag/option on the tailwind CLI. In theory, if you're not using webpack, gulp, or any bundler, you'd be using the CLI build feature to generate your CSS file.

You could do something like `tailwind build [--purge "glob"]` and be done with it. 

This way we keep it simple for new users and you can opt-in if needed.

**Comment by adamwathan** [comment]
I totally understand why you would things to work this way but I think for the reasons @benface outlined it ends up being extremely impractical and it's actually much simpler to just remove unused CSS.

The other thing to consider is that even if we tried to only generate the CSS that was used, it would still have to sort of work the same way it does now, because Tailwind would have to generate all of its classes anyways to even know what classes to actually inject in the CSS, because we'd need to compare the classes detected in the HTML to some whitelist of available classes.

Put another way there's no way to know what CSS to generate if someone uses the class `overflow-y-auto` unless we already have generated a class called `overflow-y-auto` somewhere in memory so we can grab the rules from it when doing a comparison.

Another insurmountable problem is that trying to actually parse code and detect all the classes someone is using borders on impossible, because there are so many different templating languages someone could use (HTML, Pug, ERB, Blade, Twig) and so many other ways to generate HTML (React components, Vue components, a bunch of jQuery, etc).

Trying to write code that can reliably parse and evaluate all those different input sources and extract only class names would be basically impossible. The reason Purgecss works so well is because it doesn't actually try to be smart about finding true class names, it just extracts any words from your templates and drops any CSS classes that don't match those words.

That means if you have a class like `.hello-world` and your template contains the HTML `<h1>hello-world</h1>`, Purgecss will keep the class even though it's not actually used. This ends up being the only practical way to build a tool like this because of how unrealistic it is to predict every possible way in which someone could generate HTML.

If you want a true "only generate what's needed, as needed" approach, I think your best bet is a CSS-in-JS solution like Emotion (as long as you're working in an ecosystem where that's a viable option, like building a React SPA). It's very easy to only generate the CSS that's needed in that case because you're not actually writing CSS, you're actually just writing instructions telling the tool what CSS to generate already.

Anyways, good idea and I agree it would be awesome in principal, I just don't think it's practical when the rubber meets the road.
