### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead

### ISSUE THREAD

**Issue by Youhan** [tailwindcss/tailwindcss#904]
Hi, 

I just installed Nuxt.js which has added TailwindCSS in UI Frameworks:

![image](https://user-images.githubusercontent.com/2191898/57504834-aee1df80-72bb-11e9-8917-909bd0103703.png)

When I execute 
```
yarn run dev
```
there is an error from Node says:
```
 DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead
```
using `Nuxt.js v2.6.3`

![image](https://user-images.githubusercontent.com/2191898/57504896-fa948900-72bb-11e9-92b8-79bbd10d7f71.png)

**Comment by CvX** [comment]
Tailwind doesn't have `tapable` in its dependencies.
Use `yarn why tapable` to see which package uses it, and causes this warning.

**Comment by Youhan** [comment]
@CvX Thanks
```
info This module exists because "nuxt#@nuxt#webpack#postcss-import-resolver#enhanced-resolve" depends on it.
```

**Comment by CvX** [comment]
Looks like [`postcss-import-resolver`](https://github.com/jsless/postcss-import-resolver) [uses version 3.x of](https://github.com/jsless/postcss-import-resolver/commit/62d755eb23888db7b20e2167150ea3943488be59) [`enhanced-resolve`](https://github.com/webpack/enhanced-resolve) that doesn't contain [the fix](https://github.com/webpack/enhanced-resolve/commit/d034f695c5f2510c35f0e5cd10793d1581fca889). It would have to be upgraded to 4.x.

So, the issue is with `postcss-import-resolver`. Unrelated to tailwind.

**Comment by Youhan** [comment]
This is caused by the @nuxtjs/pwa modules and will be fixed the next major version.
