### ISSUE TITLE
help running tailwind with rollup.js

### ISSUE THREAD

**Issue by cocodrino** [tailwindcss/tailwindcss#953]
Hi guys, I'm trying to integrate tailwind with a rollup project, I'm not getting any error and the css bundle file seems include many tailwind style but it's not working, the tailwind classes are not being applied, I did some small testing project so you can check

https://github.com/cocodrino/tailwind-with-rollup.js

any help would be appreciate, thank you so much

**Comment by rahmanda** [comment]
Your generated css file has [scoped selectors](https://github.com/cocodrino/tailwind-with-rollup.js/blob/6675a92c1b50da4dee2bf64aa5424346c82f042f/dest/bundle.css#L601) everywhere because you [set your postcss modules option to true](https://github.com/cocodrino/tailwind-with-rollup.js/blob/6675a92c1b50da4dee2bf64aa5424346c82f042f/rollup.config.js#L21).

To solve it you can set the modules option to false or just remove it from your configuration.

``` js
// rollup.config.js
export default {
// ...
  plugins: [
    server("dest"),
    postcss({
      extensions: [".css"],
      plugins: [simplevars, nested, cssnext],
      extract: true,
      modules: false, // set this option to false
      // ...
    })
  ]
};
```

**Comment by cocodrino** [comment]
thank you so much @rahmanda you rock...works perfect
